In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlalchemy as sql
import seaborn as sns
import os

In [2]:
tn_details_decade = pd.read_csv('tn_details_decade.csv')
tn_details_decade.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV

In [3]:
tn_fatalities_decade = pd.read_csv('tn_fatalities_decade.csv')
tn_fatalities_decade.head()

,FAT_YEARMONTH,FAT_DAY,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201607,8,30294,635269,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas
1,201607,8,30292,635264,D,07/08/2016 00:00:00,60.0,M,Camping
2,201607,8,30293,635264,D,07/08/2016 00:00:00,47.0,F,Camping
3,201605,4,30198,627799,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer
4,201607,14,31229,638992,D,07/14/2016 00:00:00,65.0,F,Under Tree

In [4]:
tn_fatalities_decade

,FAT_YEARMONTH,FAT_DAY,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201607,8,30294,635269,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas
1,201607,8,30292,635264,D,07/08/2016 00:00:00,60.0,M,Camping
2,201607,8,30293,635264,D,07/08/2016 00:00:00,47.0,F,Camping
3,201605,4,30198,627799,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer
4,201607,14,31229,638992,D,07/14/2016 00:00:00,65.0,F,Under Tree
...,...,...,...,...,...,...,...,...,...
200,202507,21,59550,1283432,D,07/21/2025 00:00:00,50.0,M,Outside/Open Areas
201,202508,12,59517,1283123,D,08/12/2025 00:00:00,29.0,M,Vehicle/Towed Trailer
202,202508,12,59518,1283123,D,08/12/2025 00:00:00,27.0,F,Vehicle/Towed Trailer
203,202508,12,59519,1283123,D,08/12/2025 00:00:00,3.0,F,Vehicle/Towed Trailer
204,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer

In [5]:
tn_fatalities_decade.columns

Index(['FAT_YEARMONTH', 'FAT_DAY', 'FATALITY_ID', 'EVENT_ID', 'FATALITY_TYPE',
       'FATALITY_DATE', 'FATALITY_AGE', 'FATALITY_SEX', 'FATALITY_LOCATION'],
      dtype='object')

In [6]:
fatalities_cleaned = tn_fatalities_decade[[
    'FATALITY_DATE','FATALITY_ID', 'EVENT_ID', 'FATALITY_TYPE', 'FATALITY_AGE', 'FATALITY_SEX', 'FATALITY_LOCATION'
]]
fatalities_cleaned.head()

,FATALITY_DATE,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,07/08/2016 00:00:00,30294,635269,D,66.0,F,Outside/Open Areas
1,07/08/2016 00:00:00,30292,635264,D,60.0,M,Camping
2,07/08/2016 00:00:00,30293,635264,D,47.0,F,Camping
3,05/04/2016 00:00:00,30198,627799,D,64.0,M,Vehicle/Towed Trailer
4,07/14/2016 00:00:00,31229,638992,D,65.0,F,Under Tree

In [7]:
fatalities_cleaned['FATALITY_DATE'] = fatalities_cleaned['FATALITY_DATE'].str[:-5]
fatalities_cleaned.head()

C:\Users\plann\AppData\Local\Temp\ipykernel_29612\3970764057.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fatalities_cleaned['FATALITY_DATE'] = fatalities_cleaned['FATALITY_DATE'].str[:-5]

,FATALITY_DATE,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,07/08/2016 00:,30294,635269,D,66.0,F,Outside/Open Areas
1,07/08/2016 00:,30292,635264,D,60.0,M,Camping
2,07/08/2016 00:,30293,635264,D,47.0,F,Camping
3,05/04/2016 00:,30198,627799,D,64.0,M,Vehicle/Towed Trailer
4,07/14/2016 00:,31229,638992,D,65.0,F,Under Tree

In [8]:
fatalities_cleaned.dtypes

FATALITY_DATE         object
FATALITY_ID            int64
EVENT_ID               int64
FATALITY_TYPE         object
FATALITY_AGE         float64
FATALITY_SEX          object
FATALITY_LOCATION     object
dtype: object

In [9]:
fatalities_cleaned.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\fatalities_cleaned.csv',index = False)

In [10]:
tn_locations_decade = pd.read_csv('tn_locations_decade.csv')
tn_locations_decade.head()

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201607,105872,635287,1,0.56,W,JENA,35.65,-84.18,3539000,8410800
1,201607,105872,635296,1,1.32,WSW,PITNER,35.87,-83.77,3552200,8346200
2,201607,105872,635301,1,1.38,S,DILL,35.56,-85.20,3533600,8512000
3,201607,105872,635299,1,0.69,N,TELLICO PLAINS,35.38,-84.30,3522800,8418000
4,201607,105948,635802,1,1.32,ENE,LOVELL,35.91,-84.13,3554600,847800

In [11]:
tn_details_decade.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV

In [12]:
tn_details_decade.columns

Index(['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME', 'END_YEARMONTH',
       'END_DAY', 'END_TIME', 'EPISODE_ID', 'EVENT_ID', 'STATE', 'STATE_FIPS',
       'YEAR', 'MONTH_NAME', 'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'BEGIN_DATE_TIME', 'CZ_TIMEZONE', 'END_DATE_TIME',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE', 'DATA_SOURCE'],
      dtype='object')

In [13]:
details_cleaned = tn_details_decade[['BEGIN_DATE_TIME','END_DATE_TIME','EPISODE_ID', 'EVENT_ID',
       'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'CZ_TIMEZONE', 
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE']]
details_cleaned.head()

,BEGIN_DATE_TIME,END_DATE_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,WFO,CZ_TIMEZONE,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16 17:55:00,08-JUL-16 17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,MRX,EST-5,...,JENA,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16 18:10:00,08-JUL-16 18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,MRX,EST-5,...,PITNER,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16 19:10:00,08-JUL-16 19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,MRX,CST-6,...,DILL,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16 18:40:00,08-JUL-16 18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,MRX,EST-5,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16 15:40:00,14-JUL-16 15:40:00,105948,635802,Hail,C,93,KNOX,MRX,EST-5,...,LOVELL,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.

In [14]:
details_cleaned.dtypes

BEGIN_DATE_TIME       object
END_DATE_TIME         object
EPISODE_ID             int64
EVENT_ID               int64
EVENT_TYPE            object
CZ_TYPE               object
CZ_FIPS                int64
CZ_NAME               object
WFO                   object
CZ_TIMEZONE           object
INJURIES_DIRECT        int64
INJURIES_INDIRECT      int64
DEATHS_DIRECT          int64
DEATHS_INDIRECT        int64
DAMAGE_PROPERTY       object
DAMAGE_CROPS          object
SOURCE                object
MAGNITUDE            float64
MAGNITUDE_TYPE        object
FLOOD_CAUSE           object
TOR_F_SCALE           object
TOR_LENGTH           float64
TOR_WIDTH            float64
TOR_OTHER_WFO         object
TOR_OTHER_CZ_FIPS    float64
TOR_OTHER_CZ_NAME     object
BEGIN_RANGE          float64
BEGIN_AZIMUTH         object
BEGIN_LOCATION        object
END_RANGE            float64
END_AZIMUTH           object
END_LOCATION          object
BEGIN_LAT            float64
BEGIN_LON            float64
END_LAT              float64
END_LON              float64
EPISODE_NARRATIVE     object
EVENT_NARRATIVE       object
dtype: object

In [15]:
details_cleaned['DAMAGE_PROPERTY'] = details_cleaned['DAMAGE_PROPERTY'].astype(str).str.replace('0.00K','0').str.replace('.','').str.replace('K','0').str.replace('M','0000').str.replace('B','0000000').str.replace('nan','0').astype(int)
details_cleaned['DAMAGE_PROPERTY'][10:20]

C:\Users\plann\AppData\Local\Temp\ipykernel_29612\380653213.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['DAMAGE_PROPERTY'] = details_cleaned['DAMAGE_PROPERTY'].astype(str).str.replace('0.00K','0').str.replace('.','').str.replace('K','0').str.replace('M','0000').str.replace('B','0000000').str.replace('nan','0').astype(int)

10    3000
11    3000
12    5000
13    1000
14       0
15       0
16       0
17       0
18       0
19       0
Name: DAMAGE_PROPERTY, dtype: int64

In [16]:
details_cleaned['DAMAGE_CROPS'] = details_cleaned['DAMAGE_CROPS'].astype(str).str.replace('0.00K','0').str.replace('.','').str.replace('K','0').str.replace('M','0000').str.replace('B','0000000').str.replace('nan','0').astype(int)
details_cleaned['DAMAGE_CROPS'][25:50]

C:\Users\plann\AppData\Local\Temp\ipykernel_29612\1443061333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['DAMAGE_CROPS'] = details_cleaned['DAMAGE_CROPS'].astype(str).str.replace('0.00K','0').str.replace('.','').str.replace('K','0').str.replace('M','0000').str.replace('B','0000000').str.replace('nan','0').astype(int)

25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
Name: DAMAGE_CROPS, dtype: int64

In [17]:
details_cleaned['SOURCE']

0                   Public
1           State Official
2           State Official
3           State Official
4          Trained Spotter
               ...
15459         Social Media
15460                 AWSS
15461      Trained Spotter
15462    Emergency Manager
15463               Public
Name: SOURCE, Length: 15464, dtype: object

In [18]:
details_cleaned.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\details_cleaned.csv',index = False)

In [19]:
details_cleaned[['BEGIN_DATE_TIME', 'END_DATE_TIME',  'EPISODE_ID', 'EVENT_ID', 'FLOOD_CAUSE',	'CATEGORY', 'TOR_F_SCALE',	'TOR_LENGTH',	'TOR_WIDTH', 'TOR_OTHER_WFO',	'TOR_OTHER_CZ_FIPS',	'TOR_OTHER_CZ_NAME']].loc[details_cleaned['BEGIN_DATE_TIME']== '08-JUL-16 17:55:00']

KeyError: "['CATEGORY'] not in index"

In [ ]:
sci_desc = ['FLOOD_CAUSE','CATEGORY','TOR_F_SCALE','TOR_LENGTH','TOR_WIDTH', 'TOR_OTHER_WFO','TOR_OTHER_CZ_FIPS','TOR_OTHER_CZ_NAME']

for desc in sci_desc:
    print(details_cleaned[f'{desc}'].loc[details_cleaned[f'{desc}'] != 'NaN'])

In [ ]:
details_cleaned.columns

In [ ]:
details_columns = ['BEGIN_DATE_TIME', 'END_DATE_TIME', 'EPISODE_ID', 'EVENT_ID',
       'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME', 'WFO', 'CZ_TIMEZONE',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_FIPS',
       'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE', 'BEGIN_AZIMUTH', 'BEGIN_LOCATION',
       'END_RANGE', 'END_AZIMUTH', 'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON',
       'END_LAT', 'END_LON', 'EPISODE_NARRATIVE', 'EVENT_NARRATIVE']

In [ ]:
columns_df = pd.DataFrame(details_columns, columns = ['list'])
columns_df

In [ ]:
columns_df['list'].str.lower()

In [ ]:
tn_locations_decade.columns

In [ ]:
tn_locations_decade.dtypes

In [ ]:
tn_locations_decade['LAT2'].describe()

In [ ]:
locations_cleaned = tn_locations_decade[['YEARMONTH', 'EPISODE_ID', 'EVENT_ID', 'LOCATION_INDEX', 'RANGE',
       'AZIMUTH', 'LOCATION', 'LATITUDE', 'LONGITUDE']]

locations_cleaned = locations_cleaned.drop_duplicates()
locations_cleaned

In [ ]:
locations_cleaned.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\locations_cleaned.csv',index = False)