In [1]:
import pandas as pd
import numpy as np
import os

### this notebook primarily joins 10 years of csvs from the NOAA Storm Events database

In [2]:
#setting storm detail csvs to variables

details_2016 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2016_c20260323.csv')
details_2017 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2017_c20260519.csv')
details_2018 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2018_c20260323.csv')
details_2019 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2019_c20260323.csv')
details_2020 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2020_c20260323.csv')
details_2021 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2021_c20260323.csv')
details_2022 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2022_c20260625.csv')
details_2023 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2023_c20260323.csv')
details_2024 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2024_c20260421.csv')
details_2025 = pd.read_csv('../noaa_data/StormEvents_details-ftp_v1.0_d2025_c20260526.csv')

In [3]:
#combining separate csv records of storm details

details_decade = pd.concat(
    [details_2016 ,details_2017 ,details_2018 ,details_2019 ,details_2020 ,details_2021 ,details_2022 ,details_2023 ,details_2024 ,details_2025]
)

In [4]:
details_decade

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201606,22,2010,201606,22,2015,107879,647809,ILLINOIS,17,...,2.00,NNW,LANGHAM,41.3406,-88.592,41.3303,-88.5632,"The evening of Wednesday, June 22 brought a fa...",This is a continuation of the tornado that beg...,CSV
1,201607,15,1715,201607,15,1715,108769,651823,SOUTH CAROLINA,45,...,0.69,N,BOYD HILL,34.9400,-81.030,34.9400,-81.0300,Scattered thunderstorms developed across the U...,One to two feet of deep standing water develop...,CSV
2,201607,15,1725,201607,15,1725,108769,651825,SOUTH CAROLINA,45,...,0.69,S,FT MILL,35.0100,-80.930,35.0100,-80.9300,Scattered thunderstorms developed across the U...,NWS Columbia relayed a report of trees blown d...,CSV
3,201607,16,1246,201607,16,1246,108812,651828,NORTH CAROLINA,37,...,2.35,ENE,OLD FT,35.6400,-82.140,35.6400,-82.1400,Scattered thunderstorms developed near the Blu...,Media reported two trees blown down along I-40...,CSV
4,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.6500,-84.180,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72355,202501,10,700,202501,10,1600,199801,1237158,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An Arctic airmass was entrenched across the ea...,Generally 2 to 3 inches of snow occurred acros...,CSV
72356,202501,21,1300,202501,21,2200,199802,1241543,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,"Widespread 4 to 6 inches of snow occurred, wit...",CSV
72357,202501,21,1300,202501,21,2100,199802,1241544,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,Widespread 1 to 3 inches of snow across the co...,CSV
72358,202501,21,1400,202501,21,2100,199802,1244266,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,Widespread 1 to 2 inches of snow across Meriwe...,CSV
72359,202501,21,1400,202501,21,2100,199802,1244269,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,Widespread 1 to 2 inches of snow across Pike C...,CSV

In [5]:
details_decade.drop_duplicates().shape

(653920, 51)

In [6]:
# filtering storm details to only include records from Tennessee

tn_details_decade = details_decade.loc[details_decade['STATE'] == 'TENNESSEE']

tn_details_decade.shape

(15464, 51)

In [7]:
#resetting index after filtering
tn_details_decade = tn_details_decade.reset_index(drop=True)
tn_details_decade

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,202509,27,1200,202509,27,1400,207597,1294715,TENNESSEE,47,...,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,CSV
15460,202509,27,1035,202509,27,1235,207597,1294716,TENNESSEE,47,...,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",CSV
15461,202509,27,1053,202509,27,1253,207597,1294717,TENNESSEE,47,...,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,CSV
15462,202509,27,1145,202509,27,1345,207597,1294718,TENNESSEE,47,...,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,CSV
15463,202509,6,400,202509,6,435,207573,1294606,TENNESSEE,47,...,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,CSV

In [8]:
tn_details_decade

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,202509,27,1200,202509,27,1400,207597,1294715,TENNESSEE,47,...,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,CSV
15460,202509,27,1035,202509,27,1235,207597,1294716,TENNESSEE,47,...,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",CSV
15461,202509,27,1053,202509,27,1253,207597,1294717,TENNESSEE,47,...,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,CSV
15462,202509,27,1145,202509,27,1345,207597,1294718,TENNESSEE,47,...,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,CSV
15463,202509,6,400,202509,6,435,207573,1294606,TENNESSEE,47,...,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,CSV

In [9]:
#saving changes to a new csv file and folder path
tn_details_decade.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\TN_storms\python_cleaning\tn_details_decade.csv',index = False)