In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlalchemy as sql
import seaborn as sns
import os

In [2]:
#saving csvs to variables

fatalities_2016 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2016_c20260323.csv')
fatalities_2017 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2017_c20260519.csv')
fatalities_2018 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2018_c20260323.csv')
fatalities_2019 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2019_c20260323.csv')
fatalities_2020 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2020_c20260323.csv')
fatalities_2021 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2021_c20260323.csv')
fatalities_2022 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2022_c20260625.csv')
fatalities_2023 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2023_c20260323.csv')
fatalities_2024 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2024_c20260421.csv')
fatalities_2025 = pd.read_csv('StormEvents_fatalities-ftp_v1.0_d2025_c20260526.csv')

In [3]:
#combining separate csv records of storm fatalities

fatalities_decade = pd.concat(
    [fatalities_2016, fatalities_2017, fatalities_2018, fatalities_2019, fatalities_2020, fatalities_2021, fatalities_2022, fatalities_2023, fatalities_2024, fatalities_2025]
)

In [4]:
fatalities_decade

,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201601,24,0,29746,609334,I,01/24/2016 00:00:00,NaN,M,Outside/Open Areas
1,201601,24,0,29747,609340,I,01/24/2016 00:00:00,70.0,M,Permanent Home
2,201601,24,0,29748,609340,I,01/24/2016 00:00:00,76.0,M,Permanent Home
3,201601,17,0,29701,609389,D,01/17/2016 00:00:00,58.0,M,Mobile/Trailer Home
4,201601,17,0,29702,609389,D,01/17/2016 00:00:00,51.0,F,Mobile/Trailer Home
...,...,...,...,...,...,...,...,...,...,...
890,202503,1,0,58955,1247889,I,03/01/2025 00:00:00,NaN,NaN,Vehicle/Towed Trailer
891,202503,16,0,58978,1248504,D,03/16/2025 00:00:00,13.0,M,Mobile/Trailer Home
892,202503,16,0,58979,1248504,D,03/16/2025 00:00:00,11.0,M,Mobile/Trailer Home
893,202503,8,0,58977,1243740,D,03/08/2025 00:00:00,42.0,M,Vehicle/Towed Trailer
894,202502,7,0,58771,1239660,I,02/07/2025 00:00:00,NaN,NaN,Unknown

In [5]:
#ensuring there are no duplicate records the the combined dataframe
fatalities_decade.drop_duplicates().shape

(10146, 10)

In [6]:
fatalities_decade = fatalities_decade.reset_index(drop=True)
fatalities_decade.head()

,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201601,24,0,29746,609334,I,01/24/2016 00:00:00,NaN,M,Outside/Open Areas
1,201601,24,0,29747,609340,I,01/24/2016 00:00:00,70.0,M,Permanent Home
2,201601,24,0,29748,609340,I,01/24/2016 00:00:00,76.0,M,Permanent Home
3,201601,17,0,29701,609389,D,01/17/2016 00:00:00,58.0,M,Mobile/Trailer Home
4,201601,17,0,29702,609389,D,01/17/2016 00:00:00,51.0,F,Mobile/Trailer Home

In [7]:
#setting storm detail csvs to variables

details_2016 = pd.read_csv('StormEvents_details-ftp_v1.0_d2016_c20260323.csv')
details_2017 = pd.read_csv('StormEvents_details-ftp_v1.0_d2017_c20260519.csv')
details_2018 = pd.read_csv('StormEvents_details-ftp_v1.0_d2018_c20260323.csv')
details_2019 = pd.read_csv('StormEvents_details-ftp_v1.0_d2019_c20260323.csv')
details_2020 = pd.read_csv('StormEvents_details-ftp_v1.0_d2020_c20260323.csv')
details_2021 = pd.read_csv('StormEvents_details-ftp_v1.0_d2021_c20260323.csv')
details_2022 = pd.read_csv('StormEvents_details-ftp_v1.0_d2022_c20260625.csv')
details_2023 = pd.read_csv('StormEvents_details-ftp_v1.0_d2023_c20260323.csv')
details_2024 = pd.read_csv('StormEvents_details-ftp_v1.0_d2024_c20260421.csv')
details_2025 = pd.read_csv('StormEvents_details-ftp_v1.0_d2025_c20260526.csv')

In [8]:
#combining separate csv records of storm details

details_decade = pd.concat(
    [details_2016 ,details_2017 ,details_2018 ,details_2019 ,details_2020 ,details_2021 ,details_2022 ,details_2023 ,details_2024 ,details_2025]
)

In [9]:
details_decade

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201606,22,2010,201606,22,2015,107879,647809,ILLINOIS,17,...,2.00,NNW,LANGHAM,41.3406,-88.592,41.3303,-88.5632,"The evening of Wednesday, June 22 brought a fa...",This is a continuation of the tornado that beg...,CSV
1,201607,15,1715,201607,15,1715,108769,651823,SOUTH CAROLINA,45,...,0.69,N,BOYD HILL,34.9400,-81.030,34.9400,-81.0300,Scattered thunderstorms developed across the U...,One to two feet of deep standing water develop...,CSV
2,201607,15,1725,201607,15,1725,108769,651825,SOUTH CAROLINA,45,...,0.69,S,FT MILL,35.0100,-80.930,35.0100,-80.9300,Scattered thunderstorms developed across the U...,NWS Columbia relayed a report of trees blown d...,CSV
3,201607,16,1246,201607,16,1246,108812,651828,NORTH CAROLINA,37,...,2.35,ENE,OLD FT,35.6400,-82.140,35.6400,-82.1400,Scattered thunderstorms developed near the Blu...,Media reported two trees blown down along I-40...,CSV
4,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.6500,-84.180,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72355,202501,10,700,202501,10,1600,199801,1237158,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An Arctic airmass was entrenched across the ea...,Generally 2 to 3 inches of snow occurred acros...,CSV
72356,202501,21,1300,202501,21,2200,199802,1241543,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,"Widespread 4 to 6 inches of snow occurred, wit...",CSV
72357,202501,21,1300,202501,21,2100,199802,1241544,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,Widespread 1 to 3 inches of snow across the co...,CSV
72358,202501,21,1400,202501,21,2100,199802,1244266,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,Widespread 1 to 2 inches of snow across Meriwe...,CSV
72359,202501,21,1400,202501,21,2100,199802,1244269,GEORGIA,13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The second Arctic airmass of the year was entr...,Widespread 1 to 2 inches of snow across Pike C...,CSV

In [10]:
details_decade.drop_duplicates().shape

(653920, 51)

In [11]:
# filtering storm details to only include records from Tennessee

tn_details_decade = details_decade.loc[details_decade['STATE'] == 'TENNESSEE']
tn_details_decade.shape

(15464, 51)

In [12]:
tn_details_decade = tn_details_decade.reset_index(drop=True)

In [13]:
# inner joining fatality records with storm details to filter only fatalities that occurred in TN

tn_fatalities_decade = pd.merge(tn_details_decade, fatalities_decade, how = 'inner', on = 'EVENT_ID')
tn_fatalities_decade.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,DATA_SOURCE,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201607,8,1728,201607,8,1728,105872,635269,TENNESSEE,47,...,CSV,201607,8,0,30294,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas
1,201607,8,1726,201607,8,1726,105872,635264,TENNESSEE,47,...,CSV,201607,8,0,30292,D,07/08/2016 00:00:00,60.0,M,Camping
2,201607,8,1726,201607,8,1726,105872,635264,TENNESSEE,47,...,CSV,201607,8,0,30293,D,07/08/2016 00:00:00,47.0,F,Camping
3,201605,4,1640,201605,4,1640,104814,627799,TENNESSEE,47,...,CSV,201605,4,0,30198,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer
4,201607,14,1050,201607,14,1050,106440,638992,TENNESSEE,47,...,CSV,201607,14,0,31229,D,07/14/2016 00:00:00,65.0,F,Under Tree

In [14]:
tn_fatalities_decade.columns

Index(['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME', 'END_YEARMONTH',
       'END_DAY', 'END_TIME', 'EPISODE_ID', 'EVENT_ID', 'STATE', 'STATE_FIPS',
       'YEAR', 'MONTH_NAME', 'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'BEGIN_DATE_TIME', 'CZ_TIMEZONE', 'END_DATE_TIME',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE', 'DATA_SOURCE', 'FAT_YEARMONTH',
       'FAT_DAY', 'FAT_TIME', 'FATALITY_ID', 'FATALITY_TYPE', 'FATALITY_DATE',
       'FATALITY_AGE', 'FATALITY_SEX', 'FATALITY_LOCATION'],
      dtype='object')

In [15]:
fatalities_decade.columns

Index(['FAT_YEARMONTH', 'FAT_DAY', 'FAT_TIME', 'FATALITY_ID', 'EVENT_ID',
       'FATALITY_TYPE', 'FATALITY_DATE', 'FATALITY_AGE', 'FATALITY_SEX',
       'FATALITY_LOCATION'],
      dtype='object')

In [16]:
#subsetting to only include columns from the origian fatality records

tn_fatalities_decade = tn_fatalities_decade[fatalities_decade.columns]
tn_fatalities_decade.head()

,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201607,8,0,30294,635269,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas
1,201607,8,0,30292,635264,D,07/08/2016 00:00:00,60.0,M,Camping
2,201607,8,0,30293,635264,D,07/08/2016 00:00:00,47.0,F,Camping
3,201605,4,0,30198,627799,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer
4,201607,14,0,31229,638992,D,07/14/2016 00:00:00,65.0,F,Under Tree

In [17]:
#repeating the previous steps but for storm locations

locations_2016 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2016_c20260707.csv')
locations_2017 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2017_c20260707.csv')
locations_2018 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2018_c20260707.csv')
locations_2019 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2019_c20260707.csv')
locations_2020 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2020_c20260707.csv')
locations_2021 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2021_c20260707.csv')
locations_2022 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2022_c20260707.csv')
locations_2023 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2023_c20260707.csv')
locations_2024 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2024_c20260707.csv')
locations_2025 = pd.read_csv('StormEvents_locations-ftp_v1.0_d2025_c20260707.csv')

In [18]:
locations_decade = pd.concat(
    [locations_2016 ,locations_2017 ,locations_2018 ,locations_2019 ,locations_2020 ,locations_2021 ,locations_2022 ,locations_2023 ,locations_2024 ,locations_2025]
)

In [19]:
locations_decade

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201601,102999,615391,1,0.69,S,LEESVILLE,31.1400,-93.2700,318400,9316200
1,201601,102999,615392,1,1.50,SSW,DE RIDDER,30.8300,-93.2900,3049800,9317400
2,201601,102999,615393,1,0.91,NW,PITKIN,30.9400,-92.9400,3056400,9256400
3,201601,102999,615394,1,0.69,S,MANSURA,31.0600,-92.0500,313600,923000
4,201601,102999,615395,1,0.59,W,DE RIDDER,30.8500,-93.2900,3051000,9317400
...,...,...,...,...,...,...,...,...,...,...,...
51865,202510,207217,1292889,3,1.63,NNE,ERDA,40.6413,-112.2865,4038478,11217190
51866,202510,207217,1292889,4,0.44,ESE,ERDA,40.6166,-112.2929,4036996,11217574
51867,202510,207217,1292893,1,2.48,N,WARNER,40.5859,-112.3281,4035154,11219686
51868,202510,207217,1292893,2,2.28,WNW,INTERNATIONAL,40.5859,-112.2680,4035154,11216080
51869,202510,207217,1292893,3,2.69,SE,(T62)TOOELE,40.4999,-112.2677,4029994,11216062

In [20]:
locations_decade.drop_duplicates().shape

(569673, 11)

In [21]:
locations_decade = locations_decade.reset_index(drop = True)

In [22]:
tn_details_decade

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,202509,27,1200,202509,27,1400,207597,1294715,TENNESSEE,47,...,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,CSV
15460,202509,27,1035,202509,27,1235,207597,1294716,TENNESSEE,47,...,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",CSV
15461,202509,27,1053,202509,27,1253,207597,1294717,TENNESSEE,47,...,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,CSV
15462,202509,27,1145,202509,27,1345,207597,1294718,TENNESSEE,47,...,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,CSV
15463,202509,6,400,202509,6,435,207573,1294606,TENNESSEE,47,...,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,CSV

In [23]:
#again using the tn_details csvs to subset other dataframes to only include TN records
tn_locations_decade = pd.merge(tn_details_decade,locations_decade, how = 'inner', on = ['EVENT_ID','EPISODE_ID'])
tn_locations_decade.shape

(14395, 60)

In [24]:
locations_decade.columns

Index(['YEARMONTH', 'EPISODE_ID', 'EVENT_ID', 'LOCATION_INDEX', 'RANGE',
       'AZIMUTH', 'LOCATION', 'LATITUDE', 'LONGITUDE', 'LAT2', 'LON2'],
      dtype='object')

In [25]:
#resetting the locations dataframe to only include the original locations columns

tn_locations_decade = tn_locations_decade[locations_decade.columns]
tn_locations_decade.head()

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201607,105872,635287,1,0.56,W,JENA,35.65,-84.18,3539000,8410800
1,201607,105872,635296,1,1.32,WSW,PITNER,35.87,-83.77,3552200,8346200
2,201607,105872,635301,1,1.38,S,DILL,35.56,-85.20,3533600,8512000
3,201607,105872,635299,1,0.69,N,TELLICO PLAINS,35.38,-84.30,3522800,8418000
4,201607,105948,635802,1,1.32,ENE,LOVELL,35.91,-84.13,3554600,847800

In [26]:
tn_details_decade.columns

Index(['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME', 'END_YEARMONTH',
       'END_DAY', 'END_TIME', 'EPISODE_ID', 'EVENT_ID', 'STATE', 'STATE_FIPS',
       'YEAR', 'MONTH_NAME', 'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'BEGIN_DATE_TIME', 'CZ_TIMEZONE', 'END_DATE_TIME',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE', 'DATA_SOURCE'],
      dtype='object')

In [27]:
tn_details_decade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15464 entries, 0 to 15463
Data columns (total 51 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   BEGIN_YEARMONTH     15464 non-null  int64
 1   BEGIN_DAY           15464 non-null  int64
 2   BEGIN_TIME          15464 non-null  int64
 3   END_YEARMONTH       15464 non-null  int64
 4   END_DAY             15464 non-null  int64
 5   END_TIME            15464 non-null  int64
 6   EPISODE_ID          15464 non-null  int64
 7   EVENT_ID            15464 non-null  int64
 8   STATE               15464 non-null  object
 9   STATE_FIPS          15464 non-null  int64
 10  YEAR                15464 non-null  int64
 11  MONTH_NAME          15464 non-null  object
 12  EVENT_TYPE          15464 non-null  object
 13  CZ_TYPE             15464 non-null  object
 14  CZ_FIPS             15464 non-null  int64
 15  CZ_NAME             15464 non-null  object
 16  WFO                 15464 non-null  object
 17  BEGIN_DATE_TIME     15464 non-null  object
 18  CZ_TIMEZONE         15464 non-null  object
 19  END_DATE_TIME       15464 non-null  object
 20  INJURIES_DIRECT     15464 non-null  int64
 21  INJURIES_INDIRECT   15464 non-null  int64
 22  DEATHS_DIRECT       15464 non-null  int64
 23  DEATHS_INDIRECT     15464 non-null  int64
 24  DAMAGE_PROPERTY     11713 non-null  object
 25  DAMAGE_CROPS        12041 non-null  object
 26  SOURCE              15464 non-null  object
 27  MAGNITUDE           8233 non-null   float64
 28  MAGNITUDE_TYPE      6648 non-null   object
 29  FLOOD_CAUSE         1629 non-null   object
 30  CATEGORY            0 non-null      float64
 31  TOR_F_SCALE         395 non-null    object
 32  TOR_LENGTH          395 non-null    float64
 33  TOR_WIDTH           395 non-null    float64
 34  TOR_OTHER_WFO       96 non-null     object
 35  TOR_OTHER_CZ_STATE  96 non-null     object
 36  TOR_OTHER_CZ_FIPS   96 non-null     float64
 37  TOR_OTHER_CZ_NAME   96 non-null     object
 38  BEGIN_RANGE         10036 non-null  float64
 39  BEGIN_AZIMUTH       10036 non-null  object
 40  BEGIN_LOCATION      10036 non-null  object
 41  END_RANGE           10036 non-null  float64
 42  END_AZIMUTH         10036 non-null  object
 43  END_LOCATION        10036 non-null  object
 44  BEGIN_LAT           10036 non-null  float64
 45  BEGIN_LON           10036 non-null  float64
 46  END_LAT             10036 non-null  float64
 47  END_LON             10036 non-null  float64
 48  EPISODE_NARRATIVE   15464 non-null  object
 49  EVENT_NARRATIVE     14621 non-null  object
 50  DATA_SOURCE         15464 non-null  object
dtypes: float64(11), int64(15), object(25)
memory usage: 6.0+ MB

In [28]:
tn_fatalities_decade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   FAT_YEARMONTH      205 non-null    int64
 1   FAT_DAY            205 non-null    int64
 2   FAT_TIME           205 non-null    int64
 3   FATALITY_ID        205 non-null    int64
 4   EVENT_ID           205 non-null    int64
 5   FATALITY_TYPE      205 non-null    object
 6   FATALITY_DATE      205 non-null    object
 7   FATALITY_AGE       180 non-null    float64
 8   FATALITY_SEX       190 non-null    object
 9   FATALITY_LOCATION  205 non-null    object
dtypes: float64(1), int64(5), object(4)
memory usage: 16.1+ KB

In [29]:
tn_locations_decade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14395 entries, 0 to 14394
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   YEARMONTH       14395 non-null  int64
 1   EPISODE_ID      14395 non-null  int64
 2   EVENT_ID        14395 non-null  int64
 3   LOCATION_INDEX  14395 non-null  int64
 4   RANGE           14395 non-null  float64
 5   AZIMUTH         14395 non-null  object
 6   LOCATION        14395 non-null  object
 7   LATITUDE        14395 non-null  float64
 8   LONGITUDE       14395 non-null  float64
 9   LAT2            14395 non-null  int64
 10  LON2            14395 non-null  int64
dtypes: float64(3), int64(6), object(2)
memory usage: 1.2+ MB

In [30]:
tn_locations_decade.head()

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201607,105872,635287,1,0.56,W,JENA,35.65,-84.18,3539000,8410800
1,201607,105872,635296,1,1.32,WSW,PITNER,35.87,-83.77,3552200,8346200
2,201607,105872,635301,1,1.38,S,DILL,35.56,-85.20,3533600,8512000
3,201607,105872,635299,1,0.69,N,TELLICO PLAINS,35.38,-84.30,3522800,8418000
4,201607,105948,635802,1,1.32,ENE,LOVELL,35.91,-84.13,3554600,847800

In [31]:
pd.to_datetime(tn_locations_decade['YEARMONTH'],format = '%Y%m').astype(str).str[:-3]

0        2016-07
1        2016-07
2        2016-07
3        2016-07
4        2016-07
          ...
14390    2025-09
14391    2025-09
14392    2025-09
14393    2025-09
14394    2025-09
Name: YEARMONTH, Length: 14395, dtype: object

In [32]:
tn_details_decade

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,202509,27,1200,202509,27,1400,207597,1294715,TENNESSEE,47,...,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,CSV
15460,202509,27,1035,202509,27,1235,207597,1294716,TENNESSEE,47,...,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",CSV
15461,202509,27,1053,202509,27,1253,207597,1294717,TENNESSEE,47,...,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,CSV
15462,202509,27,1145,202509,27,1345,207597,1294718,TENNESSEE,47,...,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,CSV
15463,202509,6,400,202509,6,435,207573,1294606,TENNESSEE,47,...,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,CSV

In [33]:
tn_fatalities_decade.head()

,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201607,8,0,30294,635269,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas
1,201607,8,0,30292,635264,D,07/08/2016 00:00:00,60.0,M,Camping
2,201607,8,0,30293,635264,D,07/08/2016 00:00:00,47.0,F,Camping
3,201605,4,0,30198,627799,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer
4,201607,14,0,31229,638992,D,07/14/2016 00:00:00,65.0,F,Under Tree

In [34]:
tn_fatalities_decade.columns

Index(['FAT_YEARMONTH', 'FAT_DAY', 'FAT_TIME', 'FATALITY_ID', 'EVENT_ID',
       'FATALITY_TYPE', 'FATALITY_DATE', 'FATALITY_AGE', 'FATALITY_SEX',
       'FATALITY_LOCATION'],
      dtype='object')

In [35]:
tn_fatalities_decade = tn_fatalities_decade.drop(columns = 'FAT_TIME')

In [36]:
tn_fatalities_decade.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\tn_fatalities_decade.csv',index = False)

In [37]:
print(os.getcwd())  # Displays the full folder path

C:\Users\plann\Documents\Nashville Software School\Python\Capstone

In [38]:
#checking to make sure I need locations for fatalities

pd.merge(tn_fatalities_decade,tn_locations_decade, how = 'inner', on = 'EVENT_ID')

# not all fatalities have a location? But yes, it seems I do

,FAT_YEARMONTH,FAT_DAY,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION,YEARMONTH,EPISODE_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201607,8,30294,635269,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas,201607,105872,1,0.89,NE,ROCKY HILL,35.9100,-84.0200,3554600,841200
1,201607,8,30292,635264,D,07/08/2016 00:00:00,60.0,M,Camping,201607,105872,1,1.77,NE,DENNIS COVE,36.2900,-82.1000,3617400,826000
2,201607,8,30293,635264,D,07/08/2016 00:00:00,47.0,F,Camping,201607,105872,1,1.77,NE,DENNIS COVE,36.2900,-82.1000,3617400,826000
3,201605,4,30198,627799,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer,201605,104814,1,0.44,WSW,MILTON,35.9276,-86.2073,3555656,8612438
4,201607,14,31229,638992,D,07/14/2016 00:00:00,65.0,F,Under Tree,201607,106440,1,1.20,WNW,FT HENRY,36.4871,-88.0397,3629226,882382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer,202508,205640,3,0.11,NNE,RYALL SPGS,35.0015,-85.1193,3590,857158
329,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer,202508,205640,4,1.72,W,RYALL SPGS,35.0008,-85.1504,3548,859024
330,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer,202508,205640,5,0.65,S,EAST BRAINERD,35.0107,-85.1695,35642,8510170
331,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer,202508,205640,1,0.92,N,WORLEY,35.0431,-85.1527,352586,859162
332,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer,202508,205640,2,1.10,ENE,WORLEY,35.0375,-85.1329,352250,857974

In [39]:
tn_fatalities_decade

,FAT_YEARMONTH,FAT_DAY,FATALITY_ID,EVENT_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION
0,201607,8,30294,635269,D,07/08/2016 00:00:00,66.0,F,Outside/Open Areas
1,201607,8,30292,635264,D,07/08/2016 00:00:00,60.0,M,Camping
2,201607,8,30293,635264,D,07/08/2016 00:00:00,47.0,F,Camping
3,201605,4,30198,627799,D,05/04/2016 00:00:00,64.0,M,Vehicle/Towed Trailer
4,201607,14,31229,638992,D,07/14/2016 00:00:00,65.0,F,Under Tree
...,...,...,...,...,...,...,...,...,...
200,202507,21,59550,1283432,D,07/21/2025 00:00:00,50.0,M,Outside/Open Areas
201,202508,12,59517,1283123,D,08/12/2025 00:00:00,29.0,M,Vehicle/Towed Trailer
202,202508,12,59518,1283123,D,08/12/2025 00:00:00,27.0,F,Vehicle/Towed Trailer
203,202508,12,59519,1283123,D,08/12/2025 00:00:00,3.0,F,Vehicle/Towed Trailer
204,202508,12,59815,1287783,D,08/12/2025 00:00:00,NaN,M,Vehicle/Towed Trailer

In [40]:
tn_locations_decade.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\tn_locations_decade.csv',index = False)

In [41]:
tn_locations_decade.head()

,YEARMONTH,EPISODE_ID,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,LON2
0,201607,105872,635287,1,0.56,W,JENA,35.65,-84.18,3539000,8410800
1,201607,105872,635296,1,1.32,WSW,PITNER,35.87,-83.77,3552200,8346200
2,201607,105872,635301,1,1.38,S,DILL,35.56,-85.20,3533600,8512000
3,201607,105872,635299,1,0.69,N,TELLICO PLAINS,35.38,-84.30,3522800,8418000
4,201607,105948,635802,1,1.32,ENE,LOVELL,35.91,-84.13,3554600,847800

In [42]:
tn_details_decade.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\tn_details_decade.csv',index = False)

In [43]:
tn_details_decade.columns

Index(['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME', 'END_YEARMONTH',
       'END_DAY', 'END_TIME', 'EPISODE_ID', 'EVENT_ID', 'STATE', 'STATE_FIPS',
       'YEAR', 'MONTH_NAME', 'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'BEGIN_DATE_TIME', 'CZ_TIMEZONE', 'END_DATE_TIME',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE', 'DATA_SOURCE'],
      dtype='object')

In [44]:
('BEGIN_YEARMONTH',
	'BEGIN_DAY',
	'BEGIN_TIME',
	'END_YEARMONTH',
	'END_DAY',
	'END_TIME',
	'EPISODE_ID',
	'EVENT_ID',
	'STATE',
	'STATE_FIPS',
	'YEAR',
	'MONTH_NAME',
	'EVENT_TYPE', 
	'CZ_TYPE', 
	'CZ_FIPS', 
	'CZ_NAME',
	'WFO', 
	'BEGIN_DATE_TIME',
	'CZ_TIMEZONE',
	'END_DATE_TIME',
	'INJURIES_DIRECT',
	'INJURIES_INDIRECT', 
	'DEATHS_DIRECT',
	'DEATHS_INDIRECT', 
	'DAMAGE_PROPERTY',
	'DAMAGE_CROPS',
	'SOURCE',
	'MAGNITUDE',
	'MAGNITUDE_TYPE',
	'FLOOD_CAUSE', 
	'CATEGORY', 
	'TOR_F_SCALE',
	'TOR_LENGTH',
	'TOR_WIDTH',
	'TOR_OTHER_WFO',
	'TOR_OTHER_CZ_STATE',
	'TOR_OTHER_CZ_FIPS',
	'TOR_OTHER_CZ_NAME', 
	'BEGIN_RANGE',
	'BEGIN_AZIMUTH', 
	'BEGIN_LOCATION', 
	'END_RANGE', 
	'END_AZIMUTH',
	'END_LOCATION',
	'BEGIN_LAT', 
	'BEGIN_LON', 
	'END_LAT',
	'END_LON',
	'EPISODE_NARRATIVE',
	'EVENT_NARRATIVE',
	'DATA_SOURCE').str.replace("'", '')

AttributeError: 'tuple' object has no attribute 'str'

In [ ]:
tn_locations_decade