In [1]:
import pandas as pd
import numpy as np
import os

### This notebook cleans the csv containing storm details so that aggregations are easier

In [2]:
# reading in the previously joined storm details csvs
tn_details_decade = pd.read_csv('tn_details_decade.csv')
tn_details_decade.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,201607,8,1755,201607,8,1755,105872,635287,TENNESSEE,47,...,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,CSV
1,201607,8,1810,201607,8,1810,105872,635296,TENNESSEE,47,...,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,CSV
2,201607,8,1910,201607,8,1910,105872,635301,TENNESSEE,47,...,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...,CSV
3,201607,8,1840,201607,8,1840,105872,635299,TENNESSEE,47,...,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...,CSV
4,201607,14,1540,201607,14,1540,105948,635802,TENNESSEE,47,...,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,CSV

In [3]:
tn_details_decade.columns

Index(['BEGIN_YEARMONTH', 'BEGIN_DAY', 'BEGIN_TIME', 'END_YEARMONTH',
       'END_DAY', 'END_TIME', 'EPISODE_ID', 'EVENT_ID', 'STATE', 'STATE_FIPS',
       'YEAR', 'MONTH_NAME', 'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'BEGIN_DATE_TIME', 'CZ_TIMEZONE', 'END_DATE_TIME',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'CATEGORY', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE', 'DATA_SOURCE'],
      dtype='object')

In [4]:
#creating a new variable consisting of a subset of the "tn_details_decade" csv using only columns I thought may be useful
details_cleaned = tn_details_decade[['BEGIN_DATE_TIME','END_DATE_TIME','EPISODE_ID', 'EVENT_ID',
       'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME',
       'WFO', 'CZ_TIMEZONE', 
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO',
       'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE',
       'BEGIN_AZIMUTH', 'BEGIN_LOCATION', 'END_RANGE', 'END_AZIMUTH',
       'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON', 'END_LAT', 'END_LON',
       'EPISODE_NARRATIVE', 'EVENT_NARRATIVE']]
details_cleaned.head()

,BEGIN_DATE_TIME,END_DATE_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,WFO,CZ_TIMEZONE,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16 17:55:00,08-JUL-16 17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,MRX,EST-5,...,JENA,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16 18:10:00,08-JUL-16 18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,MRX,EST-5,...,PITNER,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16 19:10:00,08-JUL-16 19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,MRX,CST-6,...,DILL,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16 18:40:00,08-JUL-16 18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,MRX,EST-5,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16 15:40:00,14-JUL-16 15:40:00,105948,635802,Hail,C,93,KNOX,MRX,EST-5,...,LOVELL,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.

In [5]:
#looking to see if the datatypes are appropriately set for aggregations
details_cleaned.dtypes

BEGIN_DATE_TIME       object
END_DATE_TIME         object
EPISODE_ID             int64
EVENT_ID               int64
EVENT_TYPE            object
CZ_TYPE               object
CZ_FIPS                int64
CZ_NAME               object
WFO                   object
CZ_TIMEZONE           object
INJURIES_DIRECT        int64
INJURIES_INDIRECT      int64
DEATHS_DIRECT          int64
DEATHS_INDIRECT        int64
DAMAGE_PROPERTY       object
DAMAGE_CROPS          object
SOURCE                object
MAGNITUDE            float64
MAGNITUDE_TYPE        object
FLOOD_CAUSE           object
TOR_F_SCALE           object
TOR_LENGTH           float64
TOR_WIDTH            float64
TOR_OTHER_WFO         object
TOR_OTHER_CZ_FIPS    float64
TOR_OTHER_CZ_NAME     object
BEGIN_RANGE          float64
BEGIN_AZIMUTH         object
BEGIN_LOCATION        object
END_RANGE            float64
END_AZIMUTH           object
END_LOCATION          object
BEGIN_LAT            float64
BEGIN_LON            float64
END_LAT              float64
END_LON              float64
EPISODE_NARRATIVE     object
EVENT_NARRATIVE       object
dtype: object

In [6]:
details_cleaned['DAMAGE_PROPERTY'] = (
    details_cleaned['DAMAGE_PROPERTY'].astype(str).str.replace('0.00K','0').str.replace('.','').str.replace('K','0').str.replace('M','0000').str.replace('B','0000000').str.replace('nan','0').astype(int)
)
details_cleaned['DAMAGE_PROPERTY'][10:20]

#cleaning a column containing prefixes for thousands, millions, and billions rather than a column of only numerical data like floats

C:\Users\plann\AppData\Local\Temp\ipykernel_10180\1344734637.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['DAMAGE_PROPERTY'] = (

10    3000
11    3000
12    5000
13    1000
14       0
15       0
16       0
17       0
18       0
19       0
Name: DAMAGE_PROPERTY, dtype: int64

In [7]:
details_cleaned['DAMAGE_CROPS'] = (
    details_cleaned['DAMAGE_CROPS'].astype(str).str.replace('0.00K','0').str.replace('.','').str.replace('K','0').str.replace('M','0000').str.replace('B','0000000').str.replace('nan','0').astype(int)
)
details_cleaned['DAMAGE_CROPS'][25:50]
# same cleaning as above

C:\Users\plann\AppData\Local\Temp\ipykernel_10180\1835086236.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['DAMAGE_CROPS'] = (

25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
Name: DAMAGE_CROPS, dtype: int64

In [8]:
details_cleaned.head()

,BEGIN_DATE_TIME,END_DATE_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,WFO,CZ_TIMEZONE,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16 17:55:00,08-JUL-16 17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,MRX,EST-5,...,JENA,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16 18:10:00,08-JUL-16 18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,MRX,EST-5,...,PITNER,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16 19:10:00,08-JUL-16 19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,MRX,CST-6,...,DILL,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16 18:40:00,08-JUL-16 18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,MRX,EST-5,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16 15:40:00,14-JUL-16 15:40:00,105948,635802,Hail,C,93,KNOX,MRX,EST-5,...,LOVELL,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.

In [9]:
details_cleaned['BEGIN_DATE'] = details_cleaned['BEGIN_DATE_TIME'].str[:9]
details_cleaned['BEGIN_TIME'] = details_cleaned['BEGIN_DATE_TIME'].str[10:]
details_cleaned['END_DATE'] = details_cleaned['END_DATE_TIME'].str[:9]
details_cleaned['END_TIME'] = details_cleaned['END_DATE_TIME'].str[10:]

details_cleaned.head()
#creating new columns that separates dates and times

C:\Users\plann\AppData\Local\Temp\ipykernel_10180\82809544.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['BEGIN_DATE'] = details_cleaned['BEGIN_DATE_TIME'].str[:9]
C:\Users\plann\AppData\Local\Temp\ipykernel_10180\82809544.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['BEGIN_TIME'] = details_cleaned['BEGIN_DATE_TIME'].str[10:]
C:\Users\plann\AppData\Local\Temp\ipykernel_10180\82809544.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['END_DATE'] = details_cleaned['END_DATE_TIME'].str[:9]
C:\Users\plann\AppData\Local\Temp\ipykernel_10180\82809544.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details_cleaned['END_TIME'] = details_cleaned['END_DATE_TIME'].str[10:]

,BEGIN_DATE_TIME,END_DATE_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,WFO,CZ_TIMEZONE,...,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME
0,08-JUL-16 17:55:00,08-JUL-16 17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,MRX,EST-5,...,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,08-JUL-16,17:55:00,08-JUL-16,17:55:00
1,08-JUL-16 18:10:00,08-JUL-16 18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,MRX,EST-5,...,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,08-JUL-16,18:10:00,08-JUL-16,18:10:00
2,08-JUL-16 19:10:00,08-JUL-16 19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,MRX,CST-6,...,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...,08-JUL-16,19:10:00,08-JUL-16,19:10:00
3,08-JUL-16 18:40:00,08-JUL-16 18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,MRX,EST-5,...,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...,08-JUL-16,18:40:00,08-JUL-16,18:40:00
4,14-JUL-16 15:40:00,14-JUL-16 15:40:00,105948,635802,Hail,C,93,KNOX,MRX,EST-5,...,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,14-JUL-16,15:40:00,14-JUL-16,15:40:00

In [10]:
details_cleaned.columns

Index(['BEGIN_DATE_TIME', 'END_DATE_TIME', 'EPISODE_ID', 'EVENT_ID',
       'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME', 'WFO', 'CZ_TIMEZONE',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_FIPS',
       'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE', 'BEGIN_AZIMUTH', 'BEGIN_LOCATION',
       'END_RANGE', 'END_AZIMUTH', 'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON',
       'END_LAT', 'END_LON', 'EPISODE_NARRATIVE', 'EVENT_NARRATIVE',
       'BEGIN_DATE', 'BEGIN_TIME', 'END_DATE', 'END_TIME'],
      dtype='object')

In [11]:
details_cleaned = details_cleaned[['BEGIN_DATE', 'BEGIN_TIME', 'END_DATE', 'END_TIME','EPISODE_ID', 'EVENT_ID',
       'EVENT_TYPE', 'CZ_TYPE', 'CZ_FIPS', 'CZ_NAME', 'WFO', 'CZ_TIMEZONE',
       'INJURIES_DIRECT', 'INJURIES_INDIRECT', 'DEATHS_DIRECT',
       'DEATHS_INDIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS', 'SOURCE',
       'MAGNITUDE', 'MAGNITUDE_TYPE', 'FLOOD_CAUSE', 'TOR_F_SCALE',
       'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_FIPS',
       'TOR_OTHER_CZ_NAME', 'BEGIN_RANGE', 'BEGIN_AZIMUTH', 'BEGIN_LOCATION',
       'END_RANGE', 'END_AZIMUTH', 'END_LOCATION', 'BEGIN_LAT', 'BEGIN_LON',
       'END_LAT', 'END_LON', 'EPISODE_NARRATIVE', 'EVENT_NARRATIVE']]

details_cleaned.head()

#subsetting the dataframe to hold only date columns that are separated out into data and times

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,0.56,W,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,1.32,WSW,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,1.38,S,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,1.32,ENE,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.

In [12]:
#the NOAA Storm Events database separates counties into separate regions that include cardinality prefixes. I stripped these off for the sake of getting countywide aggregations rather than regionwide aggregations
details_cleaned['CZ_NAME'] = (
    details_cleaned['CZ_NAME'].str.replace('/SMOKY MOUNTAINS','').str.replace('NORTHWEST ','').str.replace('SOUTHEAST ', '').str.replace('EAST ','').str.replace('NORTH ', '').str.replace('WEST ', '').str.replace('SOUTH ','')
)

In [13]:
#saving changes to a csv
details_cleaned.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\TN_storms\python_cleaning\details_cleaned.csv',index = False)