In [1]:
import pandas as pd
import regex as re
import sqlalchemy as sqla
import numpy as np
from IPython.display import HTML

## need to check regex script for negative events and remove trees and home damages since I have property damages. Next I need to create severity score

In [2]:
details_cleaned = pd.read_csv('details_cleaned.csv')

In [3]:
details_cleaned

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,False,False,False
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,False,False,False
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,False,False,False
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,False,False,False
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,False,False,False
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",True,False,False
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,False,False,False
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,True,False,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [4]:
details_cleaned['CZ_NAME'].unique()

array(['LOUDON', 'SEVIER', 'BLEDSOE', 'MONROE', 'KNOX', 'MCMINN',
       'GREENE', 'DAVIDSON', 'HUMPHREYS', 'MONTGOMERY', 'COCKE', 'MARION',
       'CHEATHAM', 'DEKALB', 'FRANKLIN', 'DICKSON', 'WARREN', 'LINCOLN',
       'MOORE', 'WILSON', 'SUMNER', 'CAMPBELL', 'CARTER', 'HAMBLEN',
       'JOHNSON', 'MORGAN', 'SCOTT', 'SULLIVAN', 'UNICOI', 'WASHINGTON',
       'HAWKINS', 'ROANE', 'ANDERSON', 'CLAIBORNE', 'JEFFERSON', 'BLOUNT',
       'GRAINGER', 'SEQUATCHIE', 'CLAY', 'FENTRESS', 'OVERTON',
       'HARDEMAN', 'FAYETTE', 'MCNAIRY', 'SHELBY', 'TIPTON', 'SMITH',
       'MACON', 'ROBERTSON', 'STEWART', 'WHITE', 'UNION', 'PUTNAM',
       'CUMBERLAND', 'HAMILTON', 'PICKETT', 'COFFEE', 'WILLIAMSON',
       'MAURY', 'VAN BUREN', 'CANNON', 'MARSHALL', 'BEDFORD', 'HOUSTON',
       'HARDIN', 'MEIGS', 'GRUNDY', 'GILES', 'PERRY', 'WAYNE', 'LEWIS',
       'LAWRENCE', 'CROCKETT', 'DYER', 'GIBSON', 'MADISON', 'RHEA',
       'HENDERSON', 'DECATUR', 'BENTON', 'CARROLL', 'HICKMAN',
       'RUTHERFORD', 'LAKE', 'LAUDERDALE', 'OBION', 'WEAKLEY', 'HENRY',
       'HAYWOOD', 'JACKSON', 'CHESTER', 'POLK', 'TROUSDALE', 'BRADLEY',
       'HANCOCK'], dtype=object)

In [5]:
details_cleaned['CZ_NAME'] = details_cleaned['CZ_NAME'].str.replace('/SMOKY MOUNTAINS','').str.replace('NORTHWEST ','').str.replace('SOUTHEAST ', '').str.replace('EAST ','').str.replace('NORTH ', '').str.replace('WEST', '').str.replace('SOUTH ','').str.replace(' POLK','POLK')

In [6]:
details_cleaned

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,False,False,False
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,False,False,False
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,False,False,False
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,False,False,False
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,False,False,False
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",True,False,False
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,False,False,False
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,True,False,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [7]:
text = details_cleaned['EVENT_NARRATIVE'].astype(str).str.lower()

from collections import Counter

stopwords = {'the','a','an','of','and','or','to','in','on','at','was','were',
             'is','are','be','been','with','by','from','as','it','this','that'}

counter = Counter()
for t in text:
    words = re.findall(r"[a-z']+",t)
    for w in words:
        if w not in stopwords:
             counter[w] += 1

word_count = pd.DataFrame(counter.most_common(325), columns=['word','count'])
word_count

         word  count
0        road   5812
1        down   5185
2       trees   4831
3      county   4222
4        snow   3634
..        ...    ...
320  powerful    108
321     smith    107
322  included    107
323    couple    106
324     tower    105

[325 rows x 2 columns]

In [8]:
# import pandas as pd
# import re
# from collections import Counter

# df = pd.read_csv('details_cleaned.csv')
# text = df['EVENT_NARRATIVE'].dropna().astype(str).str.lower()

# stopwords = {'the','a','an','of','and','or','to','in','on','at','was','were',
#              'is','are','be','been','with','by','from','as','it','this','that'}

# counter = Counter()
# for t in text:
#     words = re.findall(r"[a-z']+", t)
#     counter.update(w for w in words if w not in stopwords and len(w) > 2)

# word_count = pd.DataFrame(counter.most_common(325), columns=['word','count'])
# word_count

In [9]:
def row_display(x):
    pd.options.display.max_rows = x

In [10]:
def row_default():
    pd.options.display.max_rows = 60

In [11]:
row_display(325)
word_count

             word  count
0            road   5812
1            down   5185
2           trees   4831
3          county   4222
4            snow   3634
5          inches   3460
6          across   3280
7           blown   3021
8        reported   2791
9            tree   2720
10           near   2214
11       measured   2200
12        several   2076
13        degrees   1981
14           fell   1931
15         damage   1920
16           heat   1817
17         severe   1767
18        highway   1611
19          along   1539
20          winds   1534
21        tornado   1534
22          power   1522
23        station   1497
24          index   1481
25   thunderstorm   1406
26       cocorahs   1332
27        damages   1150
28     conditions   1132
29           wind   1117
30        drought   1035
31           hail   1034
32          large    999
33             up    992
34           area    959
35      estimated    954
36         downed    950
37       numerous    948
38            one    935
39         values    931
40           roof    909
41       flooding    887
42          lines    876
43           inch    861
44       estimate    856
45          rough    856
46          creek    851
47            nan    843
48           home    807
49            mph    804
50          drive    786
51        flooded    761
52           size    756
53        knocked    737
54         around    734
55           east    728
56          roads    724
57            few    714
58          south    644
59           into    641
60          homes    639
61      indicated    637
62        maximum    637
63            two    636
64          water    629
65         street    617
66        reached    615
67       uprooted    600
68        snapped    595
69        reports    585
70          north    581
71         report    558
72           also    552
73           lane    551
74            off    544
75          miles    536
76           rain    536
77        damaged    525
78           onto    520
79        between    516
80       exceeded    511
81         caused    503
82           west    502
83         closed    495
84       multiple    493
85            old    486
86           hill    477
87          minor    468
88        quarter    466
89      northeast    463
90      including    452
91      continued    439
92          heavy    436
93          house    435
94           just    431
95            due    425
96           gust    422
97           line    422
98          where    405
99             ef    403
100       twitter    393
101        showed    383
102     destroyed    380
103         gusts    379
104             d    373
105         river    373
106           for    371
107          some    367
108       springs    361
109      observer    351
110        avenue    341
111         total    341
112      tspotter    339
113  intersection    339
114          pike    337
115        before    335
116          over    335
117            th    333
118      facebook    332
119       indices    326
120     southeast    319
121         three    317
122       extreme    311
123          mile    309
124          high    302
125          barn    301
126          time    301
127          city    299
128      snowfall    294
129        during    293
130         flash    292
131       causing    287
132    powerlines    284
133          park    283
134           ice    282
135          half    280
136         media    279
137          coop    275
138     nashville    274
139         month    274
140         radar    271
141        hollow    266
142      mountain    266
143       through    266
144         moved    265
145         flood    260
146         limbs    259
147      occurred    258
148             s    256
149           end    256
150         other    254
151       blocked    250
152   significant    248
153         early    247
154         areas    245
155     afternoon    244
156       outages    242
157         hours    236
158       touched    236
159          more    236
160          path    234
161      recorded    233
162           low    233
163      suffered    231
164      southern    229
165       airport    228
166       crossed    228
167           had    228
168          peak    227
169     emergency    226
170          then    221
171         which    221
172      freezing    220
173        social    219
174      november    219
175      improved    218
176        strong    216
177            no    216
178     tennessee    215
179             i    213
180      franklin    213
181      roadways    213
182         sleet    211
183         poles    206
184           out    206
185       another    204
186      portions    204
187           nws    200
188           its    200
189         small    197
190         below    195
191      resulted    194
192           all    193
193        photos    192
194      northern    190
195         light    189
196  temperatures    188
197      blocking    187
198     northwest    186
199         mount    185
200        excess    185
201    cumberland    181
202       october    181
203         ridge    180
204          feet    180
205           car    179
206     southwest    179
207         white    179
208        branch    179
209          well    179
210       roadway    179
211           but    179
212      straight    179
213      december    179
214   clarksville    176
215      received    176
216      observed    175
217         state    173
218        struck    173
219  outbuildings    172
220          four    171
221         storm    171
222       weather    170
223    management    170
224    widespread    170
225        school    169
226        valley    169
227         sized    164
228       vehicle    164
229         about    163
230       dickson    161
231       covered    160
232       unknown    160
233         metal    159
234          fire    159
235       spotter    158
236          side    158
237        church    157
238       evening    157
239         photo    156
240          lake    156
241       lebanon    156
242      moderate    155
243    impassable    154
244          zero    154
245       amounts    153
246            rd    153
247       dropped    153
248      injuries    152
249        totals    150
250         grove    149
251        mobile    148
252        wilson    145
253         event    145
254      rainfall    144
255         chill    143
256        nearby    142
257        nickel    142
258       trained    141
259          cove    141
260   outbuilding    141
261     september    141
262        dozens    140
263        public    140
264      building    139
265        chapel    139
266     community    138
267        middle    137
268          wide    135
269       falling    134
270          part    133
271       jackson    133
272        lifted    133
273           dry    133
274       january    131
275        spring    131
276       parkway    127
277      davidson    125
278        waters    124
279         stage    124
280            am    122
281    crossville    122
282     lightning    122
283         block    121
284           non    120
285         while    119
286           wsw    119
287          golf    119
288         began    119
289          blew    119
290            pm    118
291        juliet    118
292     developed    118
293    cookeville    117
294           oak    116
295          five    116
296       morning    116
297          long    116
298           far    115
299            se    114
300        center    114
301          many    114
302          ball    113
303           nne    113
304       eastern    113
305        sparta    112
306        washed    112
307        broken    112
308           new    111
309      lawrence    111
310          most    111
311         found    111
312        putnam    110
313  murfreesboro    110
314    additional    109
315      affected    108
316         cedar    108
317        bridge    108
318    businesses    108
319      crossing    108
320      powerful    108
321         smith    107
322      included    107
323        couple    106
324         tower    105

In [12]:
row_default()

In [13]:
details_cleaned.head()

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,35.65,-84.18,35.65,-84.18,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,False,False,False
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,35.87,-83.77,35.87,-83.77,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,False,False,False
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,35.56,-85.20,35.56,-85.20,The combination of summer heating and high low...,Several trees were reported down across the so...,False,False,False
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,35.38,-84.30,35.38,-84.30,The combination of summer heating and high low...,A few trees were reported down one mile north ...,False,False,False
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,35.91,-84.13,35.91,-84.13,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,False,False,False

In [14]:
row_display(325)
word_count

             word  count
0            road   5812
1            down   5185
2           trees   4831
3          county   4222
4            snow   3634
5          inches   3460
6          across   3280
7           blown   3021
8        reported   2791
9            tree   2720
10           near   2214
11       measured   2200
12        several   2076
13        degrees   1981
14           fell   1931
15         damage   1920
16           heat   1817
17         severe   1767
18        highway   1611
19          along   1539
20          winds   1534
21        tornado   1534
22          power   1522
23        station   1497
24          index   1481
25   thunderstorm   1406
26       cocorahs   1332
27        damages   1150
28     conditions   1132
29           wind   1117
30        drought   1035
31           hail   1034
32          large    999
33             up    992
34           area    959
35      estimated    954
36         downed    950
37       numerous    948
38            one    935
39         values    931
40           roof    909
41       flooding    887
42          lines    876
43           inch    861
44       estimate    856
45          rough    856
46          creek    851
47            nan    843
48           home    807
49            mph    804
50          drive    786
51        flooded    761
52           size    756
53        knocked    737
54         around    734
55           east    728
56          roads    724
57            few    714
58          south    644
59           into    641
60          homes    639
61      indicated    637
62        maximum    637
63            two    636
64          water    629
65         street    617
66        reached    615
67       uprooted    600
68        snapped    595
69        reports    585
70          north    581
71         report    558
72           also    552
73           lane    551
74            off    544
75          miles    536
76           rain    536
77        damaged    525
78           onto    520
79        between    516
80       exceeded    511
81         caused    503
82           west    502
83         closed    495
84       multiple    493
85            old    486
86           hill    477
87          minor    468
88        quarter    466
89      northeast    463
90      including    452
91      continued    439
92          heavy    436
93          house    435
94           just    431
95            due    425
96           gust    422
97           line    422
98          where    405
99             ef    403
100       twitter    393
101        showed    383
102     destroyed    380
103         gusts    379
104             d    373
105         river    373
106           for    371
107          some    367
108       springs    361
109      observer    351
110        avenue    341
111         total    341
112      tspotter    339
113  intersection    339
114          pike    337
115        before    335
116          over    335
117            th    333
118      facebook    332
119       indices    326
120     southeast    319
121         three    317
122       extreme    311
123          mile    309
124          high    302
125          barn    301
126          time    301
127          city    299
128      snowfall    294
129        during    293
130         flash    292
131       causing    287
132    powerlines    284
133          park    283
134           ice    282
135          half    280
136         media    279
137          coop    275
138     nashville    274
139         month    274
140         radar    271
141        hollow    266
142      mountain    266
143       through    266
144         moved    265
145         flood    260
146         limbs    259
147      occurred    258
148             s    256
149           end    256
150         other    254
151       blocked    250
152   significant    248
153         early    247
154         areas    245
155     afternoon    244
156       outages    242
157         hours    236
158       touched    236
159          more    236
160          path    234
161      recorded    233
162           low    233
163      suffered    231
164      southern    229
165       airport    228
166       crossed    228
167           had    228
168          peak    227
169     emergency    226
170          then    221
171         which    221
172      freezing    220
173        social    219
174      november    219
175      improved    218
176        strong    216
177            no    216
178     tennessee    215
179             i    213
180      franklin    213
181      roadways    213
182         sleet    211
183         poles    206
184           out    206
185       another    204
186      portions    204
187           nws    200
188           its    200
189         small    197
190         below    195
191      resulted    194
192           all    193
193        photos    192
194      northern    190
195         light    189
196  temperatures    188
197      blocking    187
198     northwest    186
199         mount    185
200        excess    185
201    cumberland    181
202       october    181
203         ridge    180
204          feet    180
205           car    179
206     southwest    179
207         white    179
208        branch    179
209          well    179
210       roadway    179
211           but    179
212      straight    179
213      december    179
214   clarksville    176
215      received    176
216      observed    175
217         state    173
218        struck    173
219  outbuildings    172
220          four    171
221         storm    171
222       weather    170
223    management    170
224    widespread    170
225        school    169
226        valley    169
227         sized    164
228       vehicle    164
229         about    163
230       dickson    161
231       covered    160
232       unknown    160
233         metal    159
234          fire    159
235       spotter    158
236          side    158
237        church    157
238       evening    157
239         photo    156
240          lake    156
241       lebanon    156
242      moderate    155
243    impassable    154
244          zero    154
245       amounts    153
246            rd    153
247       dropped    153
248      injuries    152
249        totals    150
250         grove    149
251        mobile    148
252        wilson    145
253         event    145
254      rainfall    144
255         chill    143
256        nearby    142
257        nickel    142
258       trained    141
259          cove    141
260   outbuilding    141
261     september    141
262        dozens    140
263        public    140
264      building    139
265        chapel    139
266     community    138
267        middle    137
268          wide    135
269       falling    134
270          part    133
271       jackson    133
272        lifted    133
273           dry    133
274       january    131
275        spring    131
276       parkway    127
277      davidson    125
278        waters    124
279         stage    124
280            am    122
281    crossville    122
282     lightning    122
283         block    121
284           non    120
285         while    119
286           wsw    119
287          golf    119
288         began    119
289          blew    119
290            pm    118
291        juliet    118
292     developed    118
293    cookeville    117
294           oak    116
295          five    116
296       morning    116
297          long    116
298           far    115
299            se    114
300        center    114
301          many    114
302          ball    113
303           nne    113
304       eastern    113
305        sparta    112
306        washed    112
307        broken    112
308           new    111
309      lawrence    111
310          most    111
311         found    111
312        putnam    110
313  murfreesboro    110
314    additional    109
315      affected    108
316         cedar    108
317        bridge    108
318    businesses    108
319      crossing    108
320      powerful    108
321         smith    107
322      included    107
323        couple    106
324         tower    105

In [15]:
details_cleaned['road_closures'] = details_cleaned['EVENT_NARRATIVE'].astype(str).str.contains(r'(?i)(?=\S*.(road|sr-|highway|i-|lane|rd.))(?=.*(closed|blocked|flooded|closure))')
details_cleaned

C:\Users\plann\AppData\Local\Temp\ipykernel_48268\3786352316.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  details_cleaned['road_closures'] = details_cleaned['EVENT_NARRATIVE'].astype(str).str.contains(r'(?i)(?=\S*.(road|sr-|highway|i-|lane|rd.))(?=.*(closed|blocked|flooded|closure|close))')

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,False,False,False
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,False,False,False
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,False,False,False
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,False,False,False
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,False,False,False
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",True,False,False
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,False,False,False
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,True,False,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [16]:
details_cleaned.loc[details_cleaned['road_closures'] == True]

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
150,21-JAN-16,21:00:00,23-JAN-16,00:00:00,103132,616662,Winter Storm,Z,6,MONTGOMERY,...,NaN,NaN,NaN,NaN,NaN,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...,True,True,False
151,21-JAN-16,21:00:00,23-JAN-16,10:00:00,103132,616664,Winter Storm,Z,7,ROBERTSON,...,NaN,NaN,NaN,NaN,NaN,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...,True,True,False
169,21-JAN-16,21:00:00,23-JAN-16,10:00:00,103132,616666,Winter Storm,Z,8,SUMNER,...,NaN,NaN,NaN,NaN,NaN,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...,True,True,False
179,24-FEB-16,12:00:00,24-FEB-16,12:00:00,103313,617472,High Wind,Z,46,CARTER,...,NaN,NaN,NaN,NaN,NaN,A strong low pressure system moved northeast o...,Several trees and power lines were reported do...,True,True,False
196,20-JAN-16,00:00:00,20-JAN-16,12:00:00,103131,616388,Winter Weather,Z,24,HUMPHREYS,...,NaN,NaN,NaN,NaN,NaN,A strong but fast moving winter storm pushed r...,Light freezing rain up to 1/10 of an inch fell...,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15351,07-NOV-25,16:05:00,07-NOV-25,16:05:00,207510,1294315,Thunderstorm Wind,C,43,DICKSON,...,BAKERSWORKS,36.0886,-87.2796,36.0886,-87.2796,A line of showers and thunderstorms moved acro...,Severe thunderstorm winds downed numerous tree...,True,False,False
15370,05-SEP-25,16:20:00,05-SEP-25,16:20:00,205399,1281396,Thunderstorm Wind,C,135,PERRY,...,POPE,35.5970,-88.0206,35.5970,-88.0206,A potent cold front swept through Middle Tenne...,Severe thunderstorm winds downed a tree on Cyp...,True,False,False
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",True,False,False
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,True,False,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [17]:
details_cleaned['power_outage'] = details_cleaned['EVENT_NARRATIVE'].str.contains(r'(?i)(?=.*(power|line))(?=.*(outage|lost|down|damaged))')
details_cleaned

C:\Users\plann\AppData\Local\Temp\ipykernel_48268\2922760017.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  details_cleaned['power_outage'] = details_cleaned['EVENT_NARRATIVE'].str.contains(r'(?i)(?=.*(power|line))(?=.*(outage|lost|down|damaged))')

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,False,False,False
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,False,False,False
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,False,False,False
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,False,False,False
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,False,False,False
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",True,False,False
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,False,False,False
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,True,False,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [18]:
details_cleaned.loc[details_cleaned['power_outage'] == True]

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
38,15-JUN-16,17:05:00,15-JUN-16,17:08:00,105138,640639,Thunderstorm Wind,C,103,LINCOLN,...,KIRKLAND,35.0700,-86.6400,35.0700,-86.640,A band of strong to severe thunderstorms devel...,Trees and power lines were knocked down in the...,False,True,False
135,24-FEB-16,07:30:00,24-FEB-16,07:30:00,103313,617419,Thunderstorm Wind,C,123,MONROE,...,SWEETWATER,35.5900,-84.4800,35.5900,-84.480,A strong low pressure system moved northeast o...,A few power lines were reported down one mile ...,False,True,False
144,24-FEB-16,08:40:00,24-FEB-16,08:40:00,103313,617425,Thunderstorm Wind,C,1,ANDERSON,...,SOUTH CLINTON,36.0900,-84.1300,36.0900,-84.130,A strong low pressure system moved northeast o...,Several power lines and trees were reported do...,False,True,False
145,24-FEB-16,08:40:00,24-FEB-16,08:40:00,103313,617427,Thunderstorm Wind,C,93,KNOX,...,WEST KNOXVILLE,35.9700,-83.9500,35.9700,-83.950,A strong low pressure system moved northeast o...,A few trees and power lines were reported down...,False,True,False
150,21-JAN-16,21:00:00,23-JAN-16,00:00:00,103132,616662,Winter Storm,Z,6,MONTGOMERY,...,NaN,NaN,NaN,NaN,NaN,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15451,04-SEP-25,11:30:00,04-SEP-25,11:30:00,205662,1283230,Thunderstorm Wind,C,163,SULLIVAN,...,FRIENDSHIP,36.5500,-82.0200,36.5500,-82.020,A cold front pushing through the Mid-South in ...,Several trees were downed onto powerlines by s...,False,True,False
15452,04-SEP-25,11:55:00,04-SEP-25,11:55:00,205662,1283231,Thunderstorm Wind,C,129,MORGAN,...,COALFIELD,36.0300,-84.4200,36.0300,-84.420,A cold front pushing through the Mid-South in ...,Multiple trees and powerlines blown down near ...,False,True,False
15453,04-SEP-25,12:00:00,04-SEP-25,12:00:00,205662,1283232,Thunderstorm Wind,C,59,GREENE,...,GREENEVILLE,36.1700,-82.8200,36.1700,-82.820,A cold front pushing through the Mid-South in ...,Several trees blown down onto powerlines by se...,False,True,False
15456,04-SEP-25,13:45:00,04-SEP-25,13:45:00,205662,1283235,Thunderstorm Wind,C,155,SEVIER,...,BOYDS CREEK,35.9200,-83.6800,35.9200,-83.680,A cold front pushing through the Mid-South in ...,A large tree was blown down onto powerlines by...,False,True,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.978,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [19]:
details_cleaned['tree_damage'] = details_cleaned['EVENT_NARRATIVE'].str.contains(r'(?i)(?=.*(tree))(?=.*(broke|crashed))')
details_cleaned

C:\Users\plann\AppData\Local\Temp\ipykernel_48268\3661628308.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  details_cleaned['tree_damage'] = details_cleaned['EVENT_NARRATIVE'].str.contains(r'(?i)(?=.*(tree))(?=.*(broke|crashed))')

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,road_closures,power_outage,tree_damage
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...,False,False,False
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...,False,False,False
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...,False,False,False
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...,False,False,False
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...,False,False,False
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So...",True,False,False
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...,False,False,False
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...,True,False,False
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...,True,True,False

In [20]:
pd.options.display.max_colwidth = 2000
details_cleaned['EVENT_NARRATIVE'].loc[details_cleaned['tree_damage'] == True]

544                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            A large tree fell and broke through the roof of a home in the 700 block of Honduras road.
699                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Pictures from a tSpotter Twitter report showed trees down and large limbs broken on a farm south of Coopertown.
783                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                A tree fell onto two men at 1003 Sandy Valley Road. Both men were injured and hospitalized. One suffered a facial laceration and the other man suffered a broken leg.
1137                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Large trees uprooted with lots of tree limbs down. One carport roof torn off with home shingle damage and broken windows.
1469                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             TEMA reported several trees and power lines down across Overton County. A photo shared on social media also showed a large tree limb broken in Rickman.
1802                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 City Park scoreboard and lights down. Power poles broken across the city. Minor roof damage and several trees down. Two agricultural irrigation systems overturned.
2164                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              A tSpotter Twitter report indicated a large tree was uprooted along with several large branches broken on the east side of Franklin Road in Brentwood.
2882                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Trees reported down on power lines with two broken poles on Eastover Road.
3088                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Davidson County Emergency Management reported a middle-aged homeless woman on Charlotte Avenue in Nashville died due to hypothermia from the extremely cold temperatures in the first few days of January 2018. In addition, numerous homes and businesses reported water damage from broken water pipes across Davidson County, and several water mains underneath city streets also ruptured, which resulted in hundreds of thousands of dollars in damage.

In [21]:
len(details_cleaned['EVENT_NARRATIVE'].loc[details_cleaned['tree_damage'] == True])

105

In [22]:
details_cleaned.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\TN_storms\python_cleaning\details_cleaned.csv',index = False)

In [23]:
from sqlalchemy import create_engine, text

In [24]:
database_name = 'Capstone'    # Fill this in with your lahman database name

connection_string = f"postgresql://postgres:postgres@localhost:5432/{database_name}" #creates a dynamic string based on any input

In [25]:
engine = create_engine(connection_string)

In [26]:
pd.options.display.max_colwidth = 50

In [27]:
query = '''SELECT 
	cz_name
	,COUNT(road_closures) AS road_closures
FROM storms
WHERE road_closures = 'True'
GROUP BY cz_name
ORDER BY road_closures DESC'''

with engine.connect() as connection:
    road_closures = pd.read_sql(text(query), con = connection)

road_closures

       cz_name  road_closures
0       WILSON             54
1     LAWRENCE             49
2     DAVIDSON             44
3        MAURY             38
4   WILLIAMSON             36
5       SUMNER             35
6       SHELBY             33
7       SEVIER             31
8      DICKSON             28
9         KNOX             24
10   ROBERTSON             21
11    CHEATHAM             20
12  RUTHERFORD             19
13      PUTNAM             19
14    HAMILTON             18
15  MONTGOMERY             18
16      GRUNDY             18
17      TIPTON             16
18     MADISON             16
19    CROCKETT             16
20  CUMBERLAND             15
21      BLOUNT             15
22     OVERTON             15
23      GREENE             14
24     STEWART             14
25      COFFEE             14
26     JACKSON             13
27     HICKMAN             12
28       MACON             12
29       GILES             12
30   HUMPHREYS             12
31      BENTON             11
32     HAYWOOD             11
33      CARTER             11
34     CARROLL             11
35       SMITH             11
36       HENRY             10
37       PERRY             10
38      CANNON             10
39       WHITE             10
40      MCMINN             10
41     WEAKLEY             10
42    MARSHALL             10
43     BEDFORD              9
44     HAWKINS              9
45     BRADLEY              8
46     HAMBLEN              8
47     HOUSTON              8
48       MOORE              8
49  WASHINGTON              8
50     LINCOLN              7
51    FENTRESS              7
52    FRANKLIN              7
53       SCOTT              7
54       OBION              7
55      MARION              7
56       ROANE              7
57    SULLIVAN              7
58   TROUSDALE              7
59    HARDEMAN              6
60     BLEDSOE              6
61      GIBSON              6
62      MORGAN              5
63   JEFFERSON              5
64    ANDERSON              5
65       COCKE              5
66   CLAIBORNE              5
67   HENDERSON              5
68        DYER              5
69      DEKALB              4
70       MEIGS              4
71     DECATUR              4
72      WARREN              4
73     FAYETTE              4
74    CAMPBELL              4
75     MCNAIRY              3
76        LAKE              3
77  SEQUATCHIE              3
78     PICKETT              3
79   VAN BUREN              3
80      UNICOI              3
81       WAYNE              3
82        CLAY              3
83      MONROE              3
84       UNION              3
85       LEWIS              2
86      HARDIN              2
87     CHESTER              2
88    GRAINGER              2
89     JOHNSON              1
90      LOUDON              1
91     HANCOCK              1
92        RHEA              1
93  LAUDERDALE              1

In [28]:
query = '''SELECT 
	cz_name
	,COUNT(tree_damage) AS tree_damage
FROM storms
WHERE tree_damage = 'True'
GROUP BY cz_name
ORDER BY tree_damage DESC'''

with engine.connect() as connection:
    tree_damage = pd.read_sql(text(query), con = connection)

tree_damage.head()

    cz_name  tree_damage
0    TIPTON            6
1  DAVIDSON            5
2    SHELBY            5
3   LINCOLN            4
4   FAYETTE            4

In [29]:
query = '''SELECT 
	cz_name
	,COUNT(power_outage) AS power_outage
FROM storms
WHERE power_outage = 'True'
GROUP BY cz_name
ORDER BY power_outage DESC'''

with engine.connect() as connection:
    power_outage = pd.read_sql(text(query), con = connection)

power_outage.head()

     cz_name  power_outage
0   DAVIDSON            92
1   LAWRENCE            61
2     WILSON            53
3  ROBERTSON            47
4   HAMILTON            47

In [30]:
tree_outage = pd.merge(power_outage,tree_damage, how = 'inner', on = 'cz_name')
tree_outage_closures = pd.merge(tree_outage,road_closures, how = 'inner', on = 'cz_name')
tree_outage_closures.head()

     cz_name  power_outage  tree_damage  road_closures
0   DAVIDSON            92            5             44
1     WILSON            53            2             54
2  ROBERTSON            47            1             21
3       KNOX            45            1             24
4     SHELBY            44            5             33

In [31]:
tree_outage_closures['damage_score'] = tree_outage_closures['power_outage']+tree_outage_closures['tree_damage']+tree_outage_closures['road_closures']
tree_outage_closures.sort_values(by = 'damage_score',ascending = False)

       cz_name  power_outage  tree_damage  road_closures  damage_score
0     DAVIDSON            92            5             44           141
1       WILSON            53            2             54           109
4       SHELBY            44            5             33            82
6       SUMNER            38            3             35            76
8   WILLIAMSON            33            4             36            73
3         KNOX            45            1             24            70
2    ROBERTSON            47            1             21            69
12       MAURY            25            3             38            66
5       PUTNAM            38            1             19            58
7   MONTGOMERY            33            1             18            52
14     DICKSON            23            1             28            52
10     STEWART            29            2             14            45
9      OVERTON            29            1             15            45
13  CUMBERLAND            25            2             15            42
11       HENRY            28            2             10            40
24      TIPTON            16            6             16            38
21     MADISON            17            4             16            37
16     CARROLL            22            3             11            36
15     BEDFORD            23            1              9            33
17     LINCOLN            21            4              7            32
18      BENTON            20            1             11            32
26      BLOUNT            14            1             15            30
19       WHITE            19            1             10            30
22     WEAKLEY            17            2             10            29
32      GREENE            13            1             14            28
20       OBION            18            2              7            27
29       MOORE            14            2              8            24
28      GIBSON            14            3              6            23
33    SULLIVAN            13            3              7            23
49    CROCKETT             5            1             16            22
41       GILES             9            1             12            22
23      WARREN            17            1              4            22
37     HAMBLEN            11            3              8            22
31    HARDEMAN            13            2              6            21
30     FAYETTE            13            4              4            21
27   HENDERSON            14            1              5            20
45     HAYWOOD             7            2             11            20
35       SCOTT            11            1              7            19
39  WASHINGTON            10            1              8            19
36        DYER            11            2              5            18
42       ROANE             9            2              7            18
25      LOUDON            14            1              1            16
38      DEKALB            10            1              4            15
40      MONROE            10            2              3            15
34      HARDIN            11            2              2            15
51     HAWKINS             5            1              9            15
47   TROUSDALE             6            1              7            14
43       COCKE             8            1              5            14
48     DECATUR             6            1              4            11
50        LAKE             5            2              3            10
44  LAUDERDALE             7            2              1            10
46    GRAINGER             6            1              2             9
52     CHESTER             4            1              2             7

In [32]:
details_cleaned['home_damage'] = details_cleaned['EVENT_NARRATIVE'].str.contains(r'(?i)(?=.*(home|business|residence|apartment))(?=.*(damage|repair|destroy|fell))')

C:\Users\plann\AppData\Local\Temp\ipykernel_48268\3529024316.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  details_cleaned['home_damage'] = details_cleaned['EVENT_NARRATIVE'].str.contains(r'(?i)(?=.*(home|business|residence|apartment))(?=.*(damage|repair|destroy|fell))')

In [33]:
details_cleaned.loc[details_cleaned['EVENT_NARRATIVE']== True]

Empty DataFrame
Columns: [BEGIN_DATE, BEGIN_TIME, END_DATE, END_TIME, EPISODE_ID, EVENT_ID, EVENT_TYPE, CZ_TYPE, CZ_FIPS, CZ_NAME, WFO, CZ_TIMEZONE, INJURIES_DIRECT, INJURIES_INDIRECT, DEATHS_DIRECT, DEATHS_INDIRECT, DAMAGE_PROPERTY, DAMAGE_CROPS, SOURCE, MAGNITUDE, MAGNITUDE_TYPE, FLOOD_CAUSE, TOR_F_SCALE, TOR_LENGTH, TOR_WIDTH, TOR_OTHER_WFO, TOR_OTHER_CZ_FIPS, TOR_OTHER_CZ_NAME, BEGIN_RANGE, BEGIN_AZIMUTH, BEGIN_LOCATION, END_RANGE, END_AZIMUTH, END_LOCATION, BEGIN_LAT, BEGIN_LON, END_LAT, END_LON, EPISODE_NARRATIVE, EVENT_NARRATIVE, road_closures, power_outage, tree_damage, home_damage]
Index: []

[0 rows x 44 columns]