In [1]:
import pandas as pd
import regex as re
import sqlalchemy as sqla
import numpy as np
from IPython.display import HTML

In [2]:
details_regex = pd.read_csv('details_cleaned.csv')
details_regex

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So..."
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,ELIZABETHTON,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...

In [3]:
regex_narratives = details_regex[['EPISODE_ID','EVENT_ID','EPISODE_NARRATIVE','EVENT_NARRATIVE']]
regex_narratives

,EPISODE_ID,EVENT_ID,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,105872,635287,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,105872,635296,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,105872,635301,The combination of summer heating and high low...,Several trees were reported down across the so...
3,105872,635299,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,105948,635802,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.
...,...,...,...,...
15459,207597,1294715,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...
15460,207597,1294716,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So..."
15461,207597,1294717,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...
15462,207597,1294718,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...
15463,207573,1294606,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...

In [4]:
regex_narratives.to_csv(r'C:\Users\plann\Documents\Nashville Software School\Python\Capstone\TN_storms\python_cleaning\regex_narratives.csv',index = False)

In [5]:
regex_csv = pd.read_csv('regex_narratives.csv')
regex_csv

,EPISODE_ID,EVENT_ID,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,105872,635287,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,105872,635296,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,105872,635301,The combination of summer heating and high low...,Several trees were reported down across the so...
3,105872,635299,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,105948,635802,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.
...,...,...,...,...
15459,207597,1294715,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...
15460,207597,1294716,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So..."
15461,207597,1294717,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...
15462,207597,1294718,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...
15463,207573,1294606,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...

In [6]:
regex_csv.loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('road')]

,EPISODE_ID,EVENT_ID,EPISODE_NARRATIVE,EVENT_NARRATIVE
24,102861,614749,A weak area of low pressure moved northeast al...,A quarter of an inch of freezing rain accumula...
139,103131,616290,A strong but fast moving winter storm pushed r...,"A mix of light sleet, freezing rain, and snow ..."
150,103132,616662,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...
151,103132,616664,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...
169,103132,616666,A powerful upper level low pressure system mov...,Freezing rain amounts up to 1/4 of an inch fel...
...,...,...,...,...
15321,208339,1304256,A broken line of showers and strong to severe ...,Trees were reported down near the intersection...
15351,207510,1294315,A line of showers and thunderstorms moved acro...,Severe thunderstorm winds downed numerous tree...
15354,207510,1294318,A line of showers and thunderstorms moved acro...,Estimated 60 mph winds were reported in the Be...
15370,205399,1281396,A potent cold front swept through Middle Tenne...,Severe thunderstorm winds downed a tree on Cyp...
15427,205662,1283236,A cold front pushing through the Mid-South in ...,A large tree was blown down across the road by...

In [7]:
event_narrative = regex_csv[['EVENT_ID','EVENT_NARRATIVE',]]
event_narrative

       EVENT_ID                                    EVENT_NARRATIVE
0        635287  Numerous trees were reported down in the Green...
1        635296  Numerous trees were reported down in Seymour. ...
2        635301  Several trees were reported down across the so...
3        635299  A few trees were reported down one mile north ...
4        635802             Ping pong ball size hail was reported.
...         ...                                                ...
15459   1294715  Social media video showed a small stream out o...
15460   1294716  Ridge Road, just south of the Sevier County So...
15461   1294717  A spotter reported 4 inches of water crossing ...
15462   1294718  Burden Hill Road at Eastgate Road is closed du...
15463   1294606  A severe thunderstorm produced a swath of inte...

[15464 rows x 2 columns]

In [8]:
regex_csv[['EPISODE_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('road')].reset_index(drop=True)

      EPISODE_ID                                    EVENT_NARRATIVE
0         102861  A quarter of an inch of freezing rain accumula...
1         103131  A mix of light sleet, freezing rain, and snow ...
2         103132  Freezing rain amounts up to 1/4 of an inch fel...
3         103132  Freezing rain amounts up to 1/4 of an inch fel...
4         103132  Freezing rain amounts up to 1/4 of an inch fel...
...          ...                                                ...
1339      208339  Trees were reported down near the intersection...
1340      207510  Severe thunderstorm winds downed numerous tree...
1341      207510  Estimated 60 mph winds were reported in the Be...
1342      205399  Severe thunderstorm winds downed a tree on Cyp...
1343      205662  A large tree was blown down across the road by...

[1344 rows x 2 columns]

In [9]:
regex_csv[['EPISODE_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('tree')].reset_index(drop=True)

      EPISODE_ID                                    EVENT_NARRATIVE
0         105872  Numerous trees were reported down in the Green...
1         105872  Numerous trees were reported down in Seymour. ...
2         105872  Several trees were reported down across the so...
3         105872  A few trees were reported down one mile north ...
4         105948  A tree fell onto a car four miles west southwe...
...          ...                                                ...
5564      205662  Several trees were blown down by severe thunde...
5565      205662  A large tree was blown down onto powerlines by...
5566      205662  Several trees were blown down around Mooresbur...
5567      205662  Multiple large tree limbs were broken off the ...
5568      207573  A severe thunderstorm produced a swath of inte...

[5569 rows x 2 columns]

In [10]:
regex_csv[['EPISODE_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('highway')].reset_index(drop=True)

    EPISODE_ID                                    EVENT_NARRATIVE
0       105872  Numerous trees were reported down in Seymour. ...
1       105869  A few trees were reported down along highway 1...
2       105869  A large tree was reported down along highway 2...
3       102691            A tree was reported down on highway 58.
4       105872  Several trees were downed along highway 62 two...
5       105836  A few trees were reported down in the vicinity...
6       105836  Several trees were reported down along highway...
7       110978  Structural damage was reported to several buil...
8       114822  Significant damage was reported at the Poplar ...
9       113450  National Weather Service personnel along with ...
10      114118  An EF-1 tornado touched down along Hillsboro R...
11      114735  Public reported hail of golf ball size with a ...
12      114683  The roof of a large barn was blown off on High...
13      124344  Several trees were reported down along highway...
14      126558        Two trees were reported down on highway 64.
15      133475  Manchester Police Department reported and shar...
16      128123  An NWS storm survey found several trees and po...
17      131017  A tree was knocked down and partially blocked ...
18      123182  Multiple trees down on highway between New Ber...
19      137318  Several trees were reported down along highway...
20      137124  Several small drainages off of the nearby hill...
21      135262  Several main highways were flooded and closed ...
22      137319  Several trees were reported down along highway...
23      137319           A tree was reported down on highway 441.
24      138817  Trees and power lines were blown down across W...
25      146278  This EF-1 tornado touched down along Riddle La...
26      148664  Multiple trees were reported down. At oak Ridg...
27      165322  The tornado touched down in Coalmont and quick...
28      157094  Several trees were blown down on highway 62 in...
29      170709  A barn collapsed at this location and a tree w...
30      167363         Powerline and trees down along highway 76.
31      170493  Drone video footage, social media reports and ...
32      170648  Phones lines were knocked down across the road...
33      172787  Multiple roadways flooded, from back roads to ...
34      178549  Winds gusted to over 58 mph at times resulting...
35      176229  The tornado touched down near Harrison Ferry R...
36      179615  This EF1 tornado touched down near Highway 70 ...
37      180861  Several large trees were blown down, obstructi...
38      186479  This EF-2 tornado touched down north of C.M. M...
39      191117  Several trees were blown down along the county...
40      191117  Multiple large trees were blown down by severe...
41      192788  Powerlines were blown down across a local high...
42      193316  Trees were reported down on highway 130. Time ...
43      193316  Two trees were reported down blocking a lane o...
44      195887  Flash flooding on the Nolichucky River flowed ...
45      189654  An EF1 tornado touched down east of Highway 70...
46      199989        Car submerged in flooded highway underpass.
47      201225  A tree was reported down near the intersection...
48      208339   A tree was reported down at 372 Ardmore highway.
49      208339  A tree was reported down near the intersection...
50      208339  A tree was reported down on the road near the ...
51      208339  A tree was reported down near the intersection...
52      208339  Trees were reported down near the intersection...

In [11]:
regex_csv[['EPISODE_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('I-')].reset_index(drop=True)

     EPISODE_ID                                    EVENT_NARRATIVE
0        105914  A metal awning connected to the front of a bui...
1        103132  Freezing rain amounts up to 1/4 of an inch fel...
2        103132  Freezing rain amounts up to 1/4 of an inch fel...
3        103132  Freezing rain amounts up to 1/4 of an inch fel...
4        103131  A mix of light sleet, freezing rain and up to ...
..          ...                                                ...
164      202201  A foot of water covered I-40 near Danny Thomas...
165      201973      Quarter sized hail at mile marker 93 on I-40.
166      201973  Quarter sized hail south of I-40 and the 45 by...
167      201973                      Quarter sized hail near I-40.
168      201973  Water covering up to 2 lanes on I-40 east boun...

[169 rows x 2 columns]

In [12]:
regex_csv[['EPISODE_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('outage')].reset_index(drop=True)

     EPISODE_ID                                    EVENT_NARRATIVE
0        103132  Freezing rain amounts up to 1/4 of an inch fel...
1        103132  Freezing rain amounts up to 1/4 of an inch fel...
2        103132  Freezing rain amounts up to 1/4 of an inch fel...
3        103132  Freezing rain amounts up to 1/3 of an inch fel...
4        103132  Freezing rain amounts up to 1/4 of an inch fel...
..          ...                                                ...
241      199614  Severe thunderstorm winds caused power outages...
242      203044  Numerous trees were blown down by severe thund...
243      204133  Several trees were blown down by severe thunde...
244      203047  Couple dozen medium to large trees were blown ...
245      208278  Mesonet measured 60 mph in Dover and 50 mph in...

[246 rows x 2 columns]

In [13]:
pd.options.display.max_colwidth = 2000

In [14]:
regex_csv[['EVENT_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('school')].reset_index(drop=True).count()

EVENT_ID           45
EVENT_NARRATIVE    45
dtype: int64

In [15]:
pd.options.display.max_colwidth = 50
details_cleaned = pd.read_csv('details_cleaned.csv')

In [16]:
details_cleaned

,BEGIN_DATE,BEGIN_TIME,END_DATE,END_TIME,EPISODE_ID,EVENT_ID,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,...,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE
0,08-JUL-16,17:55:00,08-JUL-16,17:55:00,105872,635287,Thunderstorm Wind,C,105,LOUDON,...,JENA,0.56,W,JENA,35.6500,-84.1800,35.6500,-84.1800,The combination of summer heating and high low...,Numerous trees were reported down in the Green...
1,08-JUL-16,18:10:00,08-JUL-16,18:10:00,105872,635296,Thunderstorm Wind,C,155,SEVIER,...,PITNER,1.32,WSW,PITNER,35.8700,-83.7700,35.8700,-83.7700,The combination of summer heating and high low...,Numerous trees were reported down in Seymour. ...
2,08-JUL-16,19:10:00,08-JUL-16,19:10:00,105872,635301,Thunderstorm Wind,C,7,BLEDSOE,...,DILL,1.38,S,DILL,35.5600,-85.2000,35.5600,-85.2000,The combination of summer heating and high low...,Several trees were reported down across the so...
3,08-JUL-16,18:40:00,08-JUL-16,18:40:00,105872,635299,Thunderstorm Wind,C,123,MONROE,...,TELLICO PLAINS,0.69,N,TELLICO PLAINS,35.3800,-84.3000,35.3800,-84.3000,The combination of summer heating and high low...,A few trees were reported down one mile north ...
4,14-JUL-16,15:40:00,14-JUL-16,15:40:00,105948,635802,Hail,C,93,KNOX,...,LOVELL,1.32,ENE,LOVELL,35.9100,-84.1300,35.9100,-84.1300,An organized area of thunderstorms moved into ...,Ping pong ball size hail was reported.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15459,27-SEP-25,12:00:00,27-SEP-25,14:00:00,207597,1294715,Flash Flood,C,73,HAWKINS,...,COLD SPGS,2.70,E,COLD SPGS,36.5342,-82.8180,36.5219,-82.8130,Numerous showers and thunderstorms developing ...,Social media video showed a small stream out o...
15460,27-SEP-25,10:35:00,27-SEP-25,12:35:00,207597,1294716,Flood,C,155,SEVIER,...,PINE GROVE,1.11,ESE,PINE GROVE,35.8154,-83.5561,35.8114,-83.5559,Numerous showers and thunderstorms developing ...,"Ridge Road, just south of the Sevier County So..."
15461,27-SEP-25,10:53:00,27-SEP-25,12:53:00,207597,1294717,Flood,C,73,HAWKINS,...,COLD SPGS,1.07,SSW,COLD SPGS,36.5009,-82.8654,36.4959,-82.8621,Numerous showers and thunderstorms developing ...,A spotter reported 4 inches of water crossing ...
15462,27-SEP-25,11:45:00,27-SEP-25,13:45:00,207597,1294718,Flood,C,155,SEVIER,...,SEVIERVILLE,1.21,SE,SEVIERVILLE,35.8609,-83.5575,35.8570,-83.5567,Numerous showers and thunderstorms developing ...,Burden Hill Road at Eastgate Road is closed du...
15463,06-SEP-25,04:00:00,06-SEP-25,04:35:00,207573,1294606,Thunderstorm Wind,C,19,CARTER,...,ELIZABETHTON,2.90,E,BULADEEN,36.3538,-82.2033,36.4675,-81.9780,An isolated severe thunderstorm ahead of a col...,A severe thunderstorm produced a swath of inte...

In [17]:
details_cleaned['CZ_NAME'].unique()

array(['LOUDON', 'SEVIER', 'BLEDSOE', 'MONROE', 'KNOX', 'MCMINN',
       'GREENE', 'DAVIDSON', 'HUMPHREYS', 'MONTGOMERY', 'COCKE', 'MARION',
       'CHEATHAM', 'DEKALB', 'FRANKLIN', 'DICKSON', 'WARREN', 'LINCOLN',
       'MOORE', 'WILSON', 'SUMNER', 'CAMPBELL', 'SOUTHEAST CARTER',
       'COCKE/SMOKY MOUNTAINS', 'NORTHWEST COCKE', 'HAMBLEN', 'JOHNSON',
       'MORGAN', 'SCOTT', 'NORTH SEVIER', 'SULLIVAN', 'UNICOI',
       'WASHINGTON', 'HAWKINS', 'ROANE', 'ANDERSON', 'CLAIBORNE',
       'JEFFERSON', 'NORTHWEST CARTER', 'NORTHWEST BLOUNT', 'GRAINGER',
       'NORTHWEST GREENE', 'SEQUATCHIE', 'CLAY', 'FENTRESS', 'OVERTON',
       'HARDEMAN', 'FAYETTE', 'MCNAIRY', 'SHELBY', 'TIPTON', 'SMITH',
       'MACON', 'ROBERTSON', 'STEWART', 'WHITE', 'UNION', 'PUTNAM',
       'CUMBERLAND', 'SOUTHEAST GREENE', 'NORTHWEST MONROE', 'HAMILTON',
       'CARTER', 'PICKETT', 'COFFEE', 'WILLIAMSON', 'MAURY', 'VAN BUREN',
       'CANNON', 'MARSHALL', 'BEDFORD', 'HOUSTON', 'HARDIN', 'MEIGS',
       'GRUNDY', 'GILES', 'PERRY', 'WAYNE', 'LEWIS', 'LAWRENCE',
       'CROCKETT', 'DYER', 'GIBSON', 'MADISON', 'RHEA', 'HENDERSON',
       'DECATUR', 'BENTON', 'CARROLL', 'HICKMAN', 'RUTHERFORD', 'LAKE',
       'LAUDERDALE', 'OBION', 'WEAKLEY', 'HENRY', 'HAYWOOD', 'JACKSON',
       'CHESTER', 'SEVIER/SMOKY MOUNTAINS', 'EAST POLK', 'TROUSDALE',
       'BRADLEY', 'POLK', 'BLOUNT', 'HANCOCK', 'BLOUNT/SMOKY MOUNTAINS',
       'SOUTHEAST MONROE', 'WEST POLK'], dtype=object)

In [23]:
details_cleaned['CZ_NAME'] = details_cleaned['CZ_NAME'].str.replace('/SMOKY MOUNTAINS','').str.replace('NORTHWEST ','').str.replace('SOUTHEAST ', '').str.replace('EAST ','').str.replace('NORTH ', '').str.replace('WEST', '').str.replace('SOUTH ','').str.replace(' POLK','POLK')

In [29]:
#details_cleaned.groupby('CZ_NAME')
len(regex_csv[['EPISODE_ID','EVENT_NARRATIVE']].loc[regex_csv['EVENT_NARRATIVE'].fillna('').str.contains('outage')])

246

In [40]:
road_str = details_cleaned.loc[details_cleaned['EVENT_NARRATIVE'].fillna('').str.contains('road')].groupby('CZ_NAME').count()

In [46]:
road_str[['EVENT_NARRATIVE']].sort_values(by = 'EVENT_NARRATIVE',ascending = False)

          EVENT_NARRATIVE
CZ_NAME
LINCOLN                87
WILSON                 77
KNOX                   49
DAVIDSON               44
SHELBY                 41
...                   ...
HANCOCK                 3
GRAINGER                3
LAKE                    3
PICKETT                 2
LOUDON                  2

[95 rows x 1 columns]